# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs

__all__ = [
    'AddonSpec',
    'ETCDSnapshotFileSpec',
    'ETCDSnapshotFileSpecS3',
    'ETCDSnapshotFileStatus',
    'ETCDSnapshotFileStatusError',
]

@pulumi.output_type
class AddonSpec(dict):
    def __init__(__self__, *,
                 checksum: Optional[str] = None,
                 source: Optional[str] = None):
        if checksum is not None:
            pulumi.set(__self__, "checksum", checksum)
        if source is not None:
            pulumi.set(__self__, "source", source)

    @property
    @pulumi.getter
    def checksum(self) -> Optional[str]:
        return pulumi.get(self, "checksum")

    @property
    @pulumi.getter
    def source(self) -> Optional[str]:
        return pulumi.get(self, "source")


@pulumi.output_type
class ETCDSnapshotFileSpec(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "nodeName":
            suggest = "node_name"
        elif key == "snapshotName":
            suggest = "snapshot_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ETCDSnapshotFileSpec. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ETCDSnapshotFileSpec.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ETCDSnapshotFileSpec.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 location: Optional[str] = None,
                 metadata: Optional[Mapping[str, str]] = None,
                 node_name: Optional[str] = None,
                 s3: Optional['outputs.ETCDSnapshotFileSpecS3'] = None,
                 snapshot_name: Optional[str] = None):
        if location is not None:
            pulumi.set(__self__, "location", location)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if node_name is not None:
            pulumi.set(__self__, "node_name", node_name)
        if s3 is not None:
            pulumi.set(__self__, "s3", s3)
        if snapshot_name is not None:
            pulumi.set(__self__, "snapshot_name", snapshot_name)

    @property
    @pulumi.getter
    def location(self) -> Optional[str]:
        return pulumi.get(self, "location")

    @property
    @pulumi.getter
    def metadata(self) -> Optional[Mapping[str, str]]:
        return pulumi.get(self, "metadata")

    @property
    @pulumi.getter(name="nodeName")
    def node_name(self) -> Optional[str]:
        return pulumi.get(self, "node_name")

    @property
    @pulumi.getter
    def s3(self) -> Optional['outputs.ETCDSnapshotFileSpecS3']:
        return pulumi.get(self, "s3")

    @property
    @pulumi.getter(name="snapshotName")
    def snapshot_name(self) -> Optional[str]:
        return pulumi.get(self, "snapshot_name")


@pulumi.output_type
class ETCDSnapshotFileSpecS3(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "endpointCA":
            suggest = "endpoint_ca"
        elif key == "skipSSLVerify":
            suggest = "skip_ssl_verify"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ETCDSnapshotFileSpecS3. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ETCDSnapshotFileSpecS3.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ETCDSnapshotFileSpecS3.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 bucket: Optional[str] = None,
                 endpoint: Optional[str] = None,
                 endpoint_ca: Optional[str] = None,
                 insecure: Optional[bool] = None,
                 prefix: Optional[str] = None,
                 region: Optional[str] = None,
                 skip_ssl_verify: Optional[bool] = None):
        if bucket is not None:
            pulumi.set(__self__, "bucket", bucket)
        if endpoint is not None:
            pulumi.set(__self__, "endpoint", endpoint)
        if endpoint_ca is not None:
            pulumi.set(__self__, "endpoint_ca", endpoint_ca)
        if insecure is not None:
            pulumi.set(__self__, "insecure", insecure)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if skip_ssl_verify is not None:
            pulumi.set(__self__, "skip_ssl_verify", skip_ssl_verify)

    @property
    @pulumi.getter
    def bucket(self) -> Optional[str]:
        return pulumi.get(self, "bucket")

    @property
    @pulumi.getter
    def endpoint(self) -> Optional[str]:
        return pulumi.get(self, "endpoint")

    @property
    @pulumi.getter(name="endpointCA")
    def endpoint_ca(self) -> Optional[str]:
        return pulumi.get(self, "endpoint_ca")

    @property
    @pulumi.getter
    def insecure(self) -> Optional[bool]:
        return pulumi.get(self, "insecure")

    @property
    @pulumi.getter
    def prefix(self) -> Optional[str]:
        return pulumi.get(self, "prefix")

    @property
    @pulumi.getter
    def region(self) -> Optional[str]:
        return pulumi.get(self, "region")

    @property
    @pulumi.getter(name="skipSSLVerify")
    def skip_ssl_verify(self) -> Optional[bool]:
        return pulumi.get(self, "skip_ssl_verify")


@pulumi.output_type
class ETCDSnapshotFileStatus(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "creationTime":
            suggest = "creation_time"
        elif key == "readyToUse":
            suggest = "ready_to_use"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ETCDSnapshotFileStatus. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ETCDSnapshotFileStatus.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ETCDSnapshotFileStatus.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 creation_time: Optional[str] = None,
                 error: Optional['outputs.ETCDSnapshotFileStatusError'] = None,
                 ready_to_use: Optional[bool] = None,
                 size: Optional[str] = None):
        if creation_time is not None:
            pulumi.set(__self__, "creation_time", creation_time)
        if error is not None:
            pulumi.set(__self__, "error", error)
        if ready_to_use is not None:
            pulumi.set(__self__, "ready_to_use", ready_to_use)
        if size is not None:
            pulumi.set(__self__, "size", size)

    @property
    @pulumi.getter(name="creationTime")
    def creation_time(self) -> Optional[str]:
        return pulumi.get(self, "creation_time")

    @property
    @pulumi.getter
    def error(self) -> Optional['outputs.ETCDSnapshotFileStatusError']:
        return pulumi.get(self, "error")

    @property
    @pulumi.getter(name="readyToUse")
    def ready_to_use(self) -> Optional[bool]:
        return pulumi.get(self, "ready_to_use")

    @property
    @pulumi.getter
    def size(self) -> Optional[str]:
        return pulumi.get(self, "size")


@pulumi.output_type
class ETCDSnapshotFileStatusError(dict):
    def __init__(__self__, *,
                 message: Optional[str] = None,
                 time: Optional[str] = None):
        if message is not None:
            pulumi.set(__self__, "message", message)
        if time is not None:
            pulumi.set(__self__, "time", time)

    @property
    @pulumi.getter
    def message(self) -> Optional[str]:
        return pulumi.get(self, "message")

    @property
    @pulumi.getter
    def time(self) -> Optional[str]:
        return pulumi.get(self, "time")


