# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SettingEtherLightingArgs', 'SettingEtherLighting']

@pulumi.input_type
class SettingEtherLightingArgs:
    def __init__(__self__, *,
                 network_overrides: pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingNetworkOverrideArgs']]]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 speed_overrides: pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingSpeedOverrideArgs']]]] = None):
        """
        The set of arguments for constructing a SettingEtherLighting resource.

        :param pulumi.Input[Sequence[pulumi.Input['SettingEtherLightingNetworkOverrideArgs']]] network_overrides: Per-network LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`network`" pulumi-lang-dotnet="`Network`" pulumi-lang-go="`network`" pulumi-lang-python="`network`" pulumi-lang-yaml="`network`" pulumi-lang-java="`network`" pulumi-lang-hcl="`network`">`network`</span>.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[Sequence[pulumi.Input['SettingEtherLightingSpeedOverrideArgs']]] speed_overrides: Per-link-speed LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`speed`" pulumi-lang-dotnet="`Speed`" pulumi-lang-go="`speed`" pulumi-lang-python="`speed`" pulumi-lang-yaml="`speed`" pulumi-lang-java="`speed`" pulumi-lang-hcl="`speed`">`speed`</span>.
        """
        if network_overrides is not None:
            pulumi.set(__self__, "network_overrides", network_overrides)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if speed_overrides is not None:
            pulumi.set(__self__, "speed_overrides", speed_overrides)

    @_builtins.property
    @pulumi.getter(name="networkOverrides")
    def network_overrides(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingNetworkOverrideArgs']]]]:
        """
        Per-network LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`network`" pulumi-lang-dotnet="`Network`" pulumi-lang-go="`network`" pulumi-lang-python="`network`" pulumi-lang-yaml="`network`" pulumi-lang-java="`network`" pulumi-lang-hcl="`network`">`network`</span>.
        """
        return pulumi.get(self, "network_overrides")

    @network_overrides.setter
    def network_overrides(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingNetworkOverrideArgs']]]]):
        pulumi.set(self, "network_overrides", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="speedOverrides")
    def speed_overrides(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingSpeedOverrideArgs']]]]:
        """
        Per-link-speed LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`speed`" pulumi-lang-dotnet="`Speed`" pulumi-lang-go="`speed`" pulumi-lang-python="`speed`" pulumi-lang-yaml="`speed`" pulumi-lang-java="`speed`" pulumi-lang-hcl="`speed`">`speed`</span>.
        """
        return pulumi.get(self, "speed_overrides")

    @speed_overrides.setter
    def speed_overrides(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingSpeedOverrideArgs']]]]):
        pulumi.set(self, "speed_overrides", value)


@pulumi.input_type
class _SettingEtherLightingState:
    def __init__(__self__, *,
                 network_overrides: pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingNetworkOverrideArgs']]]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 speed_overrides: pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingSpeedOverrideArgs']]]] = None):
        """
        Input properties used for looking up and filtering SettingEtherLighting resources.

        :param pulumi.Input[Sequence[pulumi.Input['SettingEtherLightingNetworkOverrideArgs']]] network_overrides: Per-network LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`network`" pulumi-lang-dotnet="`Network`" pulumi-lang-go="`network`" pulumi-lang-python="`network`" pulumi-lang-yaml="`network`" pulumi-lang-java="`network`" pulumi-lang-hcl="`network`">`network`</span>.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[Sequence[pulumi.Input['SettingEtherLightingSpeedOverrideArgs']]] speed_overrides: Per-link-speed LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`speed`" pulumi-lang-dotnet="`Speed`" pulumi-lang-go="`speed`" pulumi-lang-python="`speed`" pulumi-lang-yaml="`speed`" pulumi-lang-java="`speed`" pulumi-lang-hcl="`speed`">`speed`</span>.
        """
        if network_overrides is not None:
            pulumi.set(__self__, "network_overrides", network_overrides)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if speed_overrides is not None:
            pulumi.set(__self__, "speed_overrides", speed_overrides)

    @_builtins.property
    @pulumi.getter(name="networkOverrides")
    def network_overrides(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingNetworkOverrideArgs']]]]:
        """
        Per-network LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`network`" pulumi-lang-dotnet="`Network`" pulumi-lang-go="`network`" pulumi-lang-python="`network`" pulumi-lang-yaml="`network`" pulumi-lang-java="`network`" pulumi-lang-hcl="`network`">`network`</span>.
        """
        return pulumi.get(self, "network_overrides")

    @network_overrides.setter
    def network_overrides(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingNetworkOverrideArgs']]]]):
        pulumi.set(self, "network_overrides", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="speedOverrides")
    def speed_overrides(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingSpeedOverrideArgs']]]]:
        """
        Per-link-speed LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`speed`" pulumi-lang-dotnet="`Speed`" pulumi-lang-go="`speed`" pulumi-lang-python="`speed`" pulumi-lang-yaml="`speed`" pulumi-lang-java="`speed`" pulumi-lang-hcl="`speed`">`speed`</span>.
        """
        return pulumi.get(self, "speed_overrides")

    @speed_overrides.setter
    def speed_overrides(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SettingEtherLightingSpeedOverrideArgs']]]]):
        pulumi.set(self, "speed_overrides", value)


@pulumi.type_token("unifi:index/settingEtherLighting:SettingEtherLighting")
class SettingEtherLighting(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 network_overrides: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SettingEtherLightingNetworkOverrideArgs', 'SettingEtherLightingNetworkOverrideArgsDict']]]]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 speed_overrides: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SettingEtherLightingSpeedOverrideArgs', 'SettingEtherLightingSpeedOverrideArgsDict']]]]] = None,
                 __props__=None):
        """
        Create a SettingEtherLighting resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SettingEtherLightingNetworkOverrideArgs', 'SettingEtherLightingNetworkOverrideArgsDict']]]] network_overrides: Per-network LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`network`" pulumi-lang-dotnet="`Network`" pulumi-lang-go="`network`" pulumi-lang-python="`network`" pulumi-lang-yaml="`network`" pulumi-lang-java="`network`" pulumi-lang-hcl="`network`">`network`</span>.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SettingEtherLightingSpeedOverrideArgs', 'SettingEtherLightingSpeedOverrideArgsDict']]]] speed_overrides: Per-link-speed LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`speed`" pulumi-lang-dotnet="`Speed`" pulumi-lang-go="`speed`" pulumi-lang-python="`speed`" pulumi-lang-yaml="`speed`" pulumi-lang-java="`speed`" pulumi-lang-hcl="`speed`">`speed`</span>.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SettingEtherLightingArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SettingEtherLighting resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SettingEtherLightingArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SettingEtherLightingArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 network_overrides: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SettingEtherLightingNetworkOverrideArgs', 'SettingEtherLightingNetworkOverrideArgsDict']]]]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 speed_overrides: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SettingEtherLightingSpeedOverrideArgs', 'SettingEtherLightingSpeedOverrideArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SettingEtherLightingArgs.__new__(SettingEtherLightingArgs)

            __props__.__dict__["network_overrides"] = network_overrides
            __props__.__dict__["site"] = site
            __props__.__dict__["speed_overrides"] = speed_overrides
        super(SettingEtherLighting, __self__).__init__(
            'unifi:index/settingEtherLighting:SettingEtherLighting',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            network_overrides: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SettingEtherLightingNetworkOverrideArgs', 'SettingEtherLightingNetworkOverrideArgsDict']]]]] = None,
            site: pulumi.Input[Optional[_builtins.str]] = None,
            speed_overrides: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SettingEtherLightingSpeedOverrideArgs', 'SettingEtherLightingSpeedOverrideArgsDict']]]]] = None) -> 'SettingEtherLighting':
        """
        Get an existing SettingEtherLighting resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SettingEtherLightingNetworkOverrideArgs', 'SettingEtherLightingNetworkOverrideArgsDict']]]] network_overrides: Per-network LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`network`" pulumi-lang-dotnet="`Network`" pulumi-lang-go="`network`" pulumi-lang-python="`network`" pulumi-lang-yaml="`network`" pulumi-lang-java="`network`" pulumi-lang-hcl="`network`">`network`</span>.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SettingEtherLightingSpeedOverrideArgs', 'SettingEtherLightingSpeedOverrideArgsDict']]]] speed_overrides: Per-link-speed LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`speed`" pulumi-lang-dotnet="`Speed`" pulumi-lang-go="`speed`" pulumi-lang-python="`speed`" pulumi-lang-yaml="`speed`" pulumi-lang-java="`speed`" pulumi-lang-hcl="`speed`">`speed`</span>.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SettingEtherLightingState.__new__(_SettingEtherLightingState)

        __props__.__dict__["network_overrides"] = network_overrides
        __props__.__dict__["site"] = site
        __props__.__dict__["speed_overrides"] = speed_overrides
        return SettingEtherLighting(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="networkOverrides")
    def network_overrides(self) -> pulumi.Output[Sequence['outputs.SettingEtherLightingNetworkOverride']]:
        """
        Per-network LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`network`" pulumi-lang-dotnet="`Network`" pulumi-lang-go="`network`" pulumi-lang-python="`network`" pulumi-lang-yaml="`network`" pulumi-lang-java="`network`" pulumi-lang-hcl="`network`">`network`</span>.
        """
        return pulumi.get(self, "network_overrides")

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @_builtins.property
    @pulumi.getter(name="speedOverrides")
    def speed_overrides(self) -> pulumi.Output[Sequence['outputs.SettingEtherLightingSpeedOverride']]:
        """
        Per-link-speed LED colors, used when a device's Etherlighting <span pulumi-lang-nodejs="`mode`" pulumi-lang-dotnet="`Mode`" pulumi-lang-go="`mode`" pulumi-lang-python="`mode`" pulumi-lang-yaml="`mode`" pulumi-lang-java="`mode`" pulumi-lang-hcl="`mode`">`mode`</span> is <span pulumi-lang-nodejs="`speed`" pulumi-lang-dotnet="`Speed`" pulumi-lang-go="`speed`" pulumi-lang-python="`speed`" pulumi-lang-yaml="`speed`" pulumi-lang-java="`speed`" pulumi-lang-hcl="`speed`">`speed`</span>.
        """
        return pulumi.get(self, "speed_overrides")

