[project]
name = "kluster"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Aetf", email = "aetf@unlimited-code.works" }
]
readme = "README.md"
requires-python = ">= 3.12"

dependencies = [
    "pulumi>=3.231.0",
    "pulumi-kubernetes>=4.29.0",
    "pulumi-awsx>=2.19.0",
    "pulumi-aws>=6.61.0",
    "requests>=2.32.3",
    "jinja2>=3.1.4",
    "pulumi-crds",
    "pulumi-github>=6.4.0",
    "pulumi-kubernetes-cert-manager>=0.2.0",
]

[project.scripts]
stack = 'kluster.scripts.stack:main'
update_crds = 'kluster.scripts.update_crds:main'

[dependency-groups]
dev = [
    "ipython>=8.30.0",
    "tqdm>=4.67.1",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "ruamel-yaml>=0.19.1",
    "ruff>=0.15.11",
]
##
## Project management section
##
[tool.uv]
managed = true
default-groups = ["dev"]

[tool.uv.sources]
pulumi-crds = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/kluster"]

##
## Formatter and linter
##
[tool.ruff]
line-length = 120
# In addition to the standard set of exclusions, omit all tests, plus a specific file.
extend-exclude = ["lib"]

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

# Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

##
## Type checker
##
[tool.pyright]
venvPath = "."
venv = ".venv"

