"""What only `update_crds` reads: the renderer it runs, a source no pin locates, the groups it drops.

The chart set and the Gateway API manifest are not here: they are pins in the
`versions:` block of `Pulumi.yaml`, which the stack program installs from and
this script reads out of the file through the program's own parser
(`kluster.lib.versions`, docs/framework/pulumi.md §3.2). Nor is the generator:
the SDK is the kubernetes provider's CRD extension, declared in the same
file's `packages:` block and generated by the pinned `pulumi` CLI. What stays
is what no stack program reads — the Helm binary, with its digest; the
directories of the Cilium source tree the definitions are read from, at the ref
the Cilium chart's pin names; and the definition groups that reach the renderer
but not the bundle.

Renovate reads nothing in this file: the Helm binary moves by hand.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

from kluster.lib.versions import ChartPin

# --- Tools ----------------------------------------------------------------

#: Helm 3, deliberately: `pulumi-kubernetes`' `helm.v4.Chart` renders with the
#: Helm **3** SDK (cluster-infra.md §1.2), so rendering the CRD bundle with a
#: Helm 3 binary renders it the way the cluster will. Helm 4 is a different
#: renderer and would make this bundle a prediction about a tool nobody runs.
HELM_VERSION = '3.20.0'
HELM_URL = f'https://get.helm.sh/helm-v{HELM_VERSION}-linux-amd64.tar.gz'

#: The archive's own published digest. Recomputed on every download, so a
#: truncated or substituted tarball fails the run instead of rendering
#: something else. A version bump updates both lines together.
HELM_SHA256 = 'dbb4c8fc8e19d159d1a63dda8db655f9ffa4aac1b9a6b188b34a40957119b286'

# --- The source tree -------------------------------------------------------


@dataclass(frozen=True, kw_only=True)
class SourceTree:
    """CRD YAML that lives in a project's source tree and nowhere else.

    Cilium is the case: its chart installs no CustomResourceDefinition, because
    the agent registers its own at runtime. The definitions still exist as
    checked-in YAML at each release tag, which is what makes an offline render
    of them possible at all.

    The ref is not written here. It is the release the chart named `chart`
    pins, so the bundle describes the release the cluster runs and a chart
    bump moves both; a second copy of the version would be a second place for
    it to be wrong.
    """

    repo: str
    chart: str
    """The `<name>` of the `versions:chart-<name>` pin whose version is the tag."""

    paths: Sequence[str]

    def ref(self, pin: ChartPin) -> str:
        """The tag the chart's version is released under."""
        if pin.name != self.chart:
            raise ValueError(f'{self.repo} is read at the version of the {self.chart} chart, not of {pin.name}')
        return f'v{pin.version}'


SOURCE_TREES: Sequence[SourceTree] = (
    SourceTree(
        repo='cilium/cilium',
        chart='cilium',
        paths=(
            'pkg/k8s/apis/cilium.io/client/crds/v2',
            'pkg/k8s/apis/cilium.io/client/crds/v2alpha1',
        ),
    ),
)

#: Groups that reach the renderer but must not reach the bundle.
#:
#: `fpga.intel.com` rides along in the Intel operator chart and belongs to the
#: retired FPGA plugin; `gateway.networking.x-k8s.io` is the experimental
#: channel's *extended* group (XBackend, XMesh, XBackendTrafficPolicy), which
#: nothing here declares and whose module name collides with the standard
#: group's: the generator names a group's module after its first segment.
DROPPED_GROUPS: frozenset[str] = frozenset(
    {
        'fpga.intel.com',
        'gateway.networking.x-k8s.io',
    }
)
