# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload, Literal
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._inputs import *
import pulumi_kubernetes

__all__ = ['CiliumNetworkPolicyInitArgs', 'CiliumNetworkPolicy']

@pulumi.input_type
class CiliumNetworkPolicyInitArgs:
    def __init__(__self__, *,
                 metadata: pulumi.Input['pulumi_kubernetes.meta.v1.ObjectMetaArgs'],
                 api_version: pulumi.Input[Optional[Literal['cilium.io/v2']]] = None,
                 kind: pulumi.Input[Optional[Literal['CiliumNetworkPolicy']]] = None,
                 spec: pulumi.Input[Optional['CiliumNetworkPolicySpecArgs']] = None,
                 specs: pulumi.Input[Optional[Sequence[pulumi.Input['CiliumNetworkPolicySpecsArgs']]]] = None):
        """
        The set of arguments for constructing a CiliumNetworkPolicy resource.

        :param pulumi.Input['pulumi_kubernetes.meta.v1.ObjectMetaArgs'] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param pulumi.Input[Literal['cilium.io/v2']] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[Literal['CiliumNetworkPolicy']] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input[Sequence[pulumi.Input['CiliumNetworkPolicySpecsArgs']]] specs: Specs is a list of desired Cilium specific rule specification.
        """
        pulumi.set(__self__, "metadata", metadata)
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'cilium.io/v2')
        if kind is not None:
            pulumi.set(__self__, "kind", 'CiliumNetworkPolicy')
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if specs is not None:
            pulumi.set(__self__, "specs", specs)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input['pulumi_kubernetes.meta.v1.ObjectMetaArgs']:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input['pulumi_kubernetes.meta.v1.ObjectMetaArgs']):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Input[Optional[Literal['cilium.io/v2']]]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: pulumi.Input[Optional[Literal['cilium.io/v2']]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[Literal['CiliumNetworkPolicy']]]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[Literal['CiliumNetworkPolicy']]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Input[Optional['CiliumNetworkPolicySpecArgs']]:
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: pulumi.Input[Optional['CiliumNetworkPolicySpecArgs']]):
        pulumi.set(self, "spec", value)

    @_builtins.property
    @pulumi.getter
    def specs(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['CiliumNetworkPolicySpecsArgs']]]]:
        """
        Specs is a list of desired Cilium specific rule specification.
        """
        return pulumi.get(self, "specs")

    @specs.setter
    def specs(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['CiliumNetworkPolicySpecsArgs']]]]):
        pulumi.set(self, "specs", value)


@pulumi.type_token("crds:cilium.io/v2:CiliumNetworkPolicy")
class CiliumNetworkPolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: pulumi.Input[Optional[Literal['cilium.io/v2']]] = None,
                 kind: pulumi.Input[Optional[Literal['CiliumNetworkPolicy']]] = None,
                 metadata: pulumi.Input[Optional[pulumi.InputType['pulumi_kubernetes.meta.v1.ObjectMetaArgs']]] = None,
                 spec: pulumi.Input[Optional[Union['CiliumNetworkPolicySpecArgs', 'CiliumNetworkPolicySpecArgsDict', 'outputs.CiliumNetworkPolicySpec']]] = None,
                 specs: pulumi.Input[Optional[Sequence[pulumi.Input[Union['CiliumNetworkPolicySpecsArgs', 'CiliumNetworkPolicySpecsArgsDict', 'outputs.CiliumNetworkPolicySpecs']]]]] = None,
                 __props__=None):
        """
        CiliumNetworkPolicy is a Kubernetes third-party resource with an extended
        version of NetworkPolicy.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Literal['cilium.io/v2']] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[Literal['CiliumNetworkPolicy']] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input[pulumi.InputType['pulumi_kubernetes.meta.v1.ObjectMetaArgs']] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param pulumi.Input[Sequence[pulumi.Input[Union['CiliumNetworkPolicySpecsArgs', 'CiliumNetworkPolicySpecsArgsDict', 'outputs.CiliumNetworkPolicySpecs']]]] specs: Specs is a list of desired Cilium specific rule specification.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CiliumNetworkPolicyInitArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        CiliumNetworkPolicy is a Kubernetes third-party resource with an extended
        version of NetworkPolicy.

        :param str resource_name: The name of the resource.
        :param CiliumNetworkPolicyInitArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CiliumNetworkPolicyInitArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: pulumi.Input[Optional[Literal['cilium.io/v2']]] = None,
                 kind: pulumi.Input[Optional[Literal['CiliumNetworkPolicy']]] = None,
                 metadata: pulumi.Input[Optional[pulumi.InputType['pulumi_kubernetes.meta.v1.ObjectMetaArgs']]] = None,
                 spec: pulumi.Input[Optional[Union['CiliumNetworkPolicySpecArgs', 'CiliumNetworkPolicySpecArgsDict', 'outputs.CiliumNetworkPolicySpec']]] = None,
                 specs: pulumi.Input[Optional[Sequence[pulumi.Input[Union['CiliumNetworkPolicySpecsArgs', 'CiliumNetworkPolicySpecsArgsDict', 'outputs.CiliumNetworkPolicySpecs']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CiliumNetworkPolicyInitArgs.__new__(CiliumNetworkPolicyInitArgs)

            __props__.__dict__["api_version"] = 'cilium.io/v2'
            __props__.__dict__["kind"] = 'CiliumNetworkPolicy'
            if metadata is None and not opts.urn:
                raise TypeError("Missing required property 'metadata'")
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["spec"] = spec
            __props__.__dict__["specs"] = specs
            __props__.__dict__["status"] = None
        alias_opts = pulumi.ResourceOptions(aliases=[pulumi.Alias(type_="kubernetes:cilium.io/v2:CiliumNetworkPolicy")])
        opts = pulumi.ResourceOptions.merge(opts, alias_opts)
        super(CiliumNetworkPolicy, __self__).__init__(
            'crds:cilium.io/v2:CiliumNetworkPolicy',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'CiliumNetworkPolicy':
        """
        Get an existing CiliumNetworkPolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = CiliumNetworkPolicyInitArgs.__new__(CiliumNetworkPolicyInitArgs)

        __props__.__dict__["api_version"] = None
        __props__.__dict__["kind"] = None
        __props__.__dict__["metadata"] = None
        __props__.__dict__["spec"] = None
        __props__.__dict__["specs"] = None
        __props__.__dict__["status"] = None
        return CiliumNetworkPolicy(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Output[Literal['cilium.io/v2']]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Output[Literal['CiliumNetworkPolicy']]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['pulumi_kubernetes.meta.v1.outputs.ObjectMeta']:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Output['outputs.CiliumNetworkPolicySpec']:
        return pulumi.get(self, "spec")

    @_builtins.property
    @pulumi.getter
    def specs(self) -> pulumi.Output[Sequence['outputs.CiliumNetworkPolicySpecs']]:
        """
        Specs is a list of desired Cilium specific rule specification.
        """
        return pulumi.get(self, "specs")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[Optional['outputs.CiliumNetworkPolicyStatus']]:
        return pulumi.get(self, "status")

