# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from ... import meta as _meta

__all__ = ['CiliumIdentityInitArgs', 'CiliumIdentity']

@pulumi.input_type
class CiliumIdentityInitArgs:
    def __init__(__self__, *,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']] = None,
                 security_labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a CiliumIdentity resource.

        :param pulumi.Input[_builtins.str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[_builtins.str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input['_meta.v1.ObjectMetaArgs'] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] security_labels: SecurityLabels is the source-of-truth set of labels for this identity.
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'cilium.io/v2')
        if kind is not None:
            pulumi.set(__self__, "kind", 'CiliumIdentity')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if security_labels is not None:
            pulumi.set(__self__, "security_labels", security_labels)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter(name="security-labels")
    def security_labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        SecurityLabels is the source-of-truth set of labels for this identity.
        """
        return pulumi.get(self, "security_labels")

    @security_labels.setter
    def security_labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "security_labels", value)


@pulumi.type_token("kubernetes:cilium.io/v2:CiliumIdentity")
class CiliumIdentity(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']]] = None,
                 security_labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        CiliumIdentity is a CRD that represents an identity managed by Cilium.
        It is intended as a backing store for identity allocation, acting as the
        global coordination backend, and can be used in place of a KVStore (such as
        etcd).
        The name of the CRD is the numeric identity and the labels on the CRD object
        are the kubernetes sourced labels seen by cilium. This is currently the
        only label source possible when running under kubernetes. Non-kubernetes
        labels are filtered but all labels, from all sources, are places in the
        SecurityLabels field. These also include the source and are used to define
        the identity.
        The labels under metav1.ObjectMeta can be used when searching for
        CiliumIdentity instances that include particular labels. This can be done
        with invocations such as:

            kubectl get ciliumid -l 'foo=bar'


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[_builtins.str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] security_labels: SecurityLabels is the source-of-truth set of labels for this identity.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[CiliumIdentityInitArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        CiliumIdentity is a CRD that represents an identity managed by Cilium.
        It is intended as a backing store for identity allocation, acting as the
        global coordination backend, and can be used in place of a KVStore (such as
        etcd).
        The name of the CRD is the numeric identity and the labels on the CRD object
        are the kubernetes sourced labels seen by cilium. This is currently the
        only label source possible when running under kubernetes. Non-kubernetes
        labels are filtered but all labels, from all sources, are places in the
        SecurityLabels field. These also include the source and are used to define
        the identity.
        The labels under metav1.ObjectMeta can be used when searching for
        CiliumIdentity instances that include particular labels. This can be done
        with invocations such as:

            kubectl get ciliumid -l 'foo=bar'


        :param str resource_name: The name of the resource.
        :param CiliumIdentityInitArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CiliumIdentityInitArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']]] = None,
                 security_labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CiliumIdentityInitArgs.__new__(CiliumIdentityInitArgs)

            __props__.__dict__["api_version"] = 'cilium.io/v2'
            __props__.__dict__["kind"] = 'CiliumIdentity'
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["security_labels"] = security_labels
        super(CiliumIdentity, __self__).__init__(
            'kubernetes:cilium.io/v2:CiliumIdentity',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'CiliumIdentity':
        """
        Get an existing CiliumIdentity resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = CiliumIdentityInitArgs.__new__(CiliumIdentityInitArgs)

        __props__.__dict__["api_version"] = None
        __props__.__dict__["kind"] = None
        __props__.__dict__["metadata"] = None
        __props__.__dict__["security_labels"] = None
        return CiliumIdentity(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Output[_builtins.str]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Output[_builtins.str]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['_meta.v1.outputs.ObjectMeta']:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter(name="security-labels")
    def security_labels(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        SecurityLabels is the source-of-truth set of labels for this identity.
        """
        return pulumi.get(self, "security_labels")

