# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_crds.acme as __acme
    acme = __acme
    import pulumi_crds.barmancloud as __barmancloud
    barmancloud = __barmancloud
    import pulumi_crds.bitnami as __bitnami
    bitnami = __bitnami
    import pulumi_crds.cert_manager as __cert_manager
    cert_manager = __cert_manager
    import pulumi_crds.cilium as __cilium
    cilium = __cilium
    import pulumi_crds.deviceplugin as __deviceplugin
    deviceplugin = __deviceplugin
    import pulumi_crds.gateway as __gateway
    gateway = __gateway
    import pulumi_crds.nfd as __nfd
    nfd = __nfd
    import pulumi_crds.operator as __operator
    operator = __operator
    import pulumi_crds.postgresql as __postgresql
    postgresql = __postgresql
    import pulumi_crds.volsync as __volsync
    volsync = __volsync
else:
    acme = _utilities.lazy_import('pulumi_crds.acme')
    barmancloud = _utilities.lazy_import('pulumi_crds.barmancloud')
    bitnami = _utilities.lazy_import('pulumi_crds.bitnami')
    cert_manager = _utilities.lazy_import('pulumi_crds.cert_manager')
    cilium = _utilities.lazy_import('pulumi_crds.cilium')
    deviceplugin = _utilities.lazy_import('pulumi_crds.deviceplugin')
    gateway = _utilities.lazy_import('pulumi_crds.gateway')
    nfd = _utilities.lazy_import('pulumi_crds.nfd')
    operator = _utilities.lazy_import('pulumi_crds.operator')
    postgresql = _utilities.lazy_import('pulumi_crds.postgresql')
    volsync = _utilities.lazy_import('pulumi_crds.volsync')

