# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ... import meta as _meta
from ._inputs import *

__all__ = ['CiliumEndpointSliceInitArgs', 'CiliumEndpointSlice']

@pulumi.input_type
class CiliumEndpointSliceInitArgs:
    def __init__(__self__, *,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoints: pulumi.Input[Optional[Sequence[pulumi.Input['CiliumEndpointSliceEndpointsArgs']]]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a CiliumEndpointSlice resource.

        :param pulumi.Input[_builtins.str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[Sequence[pulumi.Input['CiliumEndpointSliceEndpointsArgs']]] endpoints: Endpoints is a list of coreCEPs packed in a CiliumEndpointSlice
        :param pulumi.Input[_builtins.str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input['_meta.v1.ObjectMetaArgs'] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param pulumi.Input[_builtins.str] namespace: Namespace indicate as CiliumEndpointSlice namespace.
               All the CiliumEndpoints within the same namespace are put together
               in CiliumEndpointSlice.
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'cilium.io/v2alpha1')
        if endpoints is not None:
            pulumi.set(__self__, "endpoints", endpoints)
        if kind is not None:
            pulumi.set(__self__, "kind", 'CiliumEndpointSlice')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['CiliumEndpointSliceEndpointsArgs']]]]:
        """
        Endpoints is a list of coreCEPs packed in a CiliumEndpointSlice
        """
        return pulumi.get(self, "endpoints")

    @endpoints.setter
    def endpoints(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['CiliumEndpointSliceEndpointsArgs']]]]):
        pulumi.set(self, "endpoints", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Namespace indicate as CiliumEndpointSlice namespace.
        All the CiliumEndpoints within the same namespace are put together
        in CiliumEndpointSlice.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "namespace", value)


@pulumi.type_token("kubernetes:cilium.io/v2alpha1:CiliumEndpointSlice")
class CiliumEndpointSlice(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoints: pulumi.Input[Optional[Sequence[pulumi.Input[Union['CiliumEndpointSliceEndpointsArgs', 'CiliumEndpointSliceEndpointsArgsDict']]]]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        CiliumEndpointSlice contains a group of CoreCiliumendpoints.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[Sequence[pulumi.Input[Union['CiliumEndpointSliceEndpointsArgs', 'CiliumEndpointSliceEndpointsArgsDict']]]] endpoints: Endpoints is a list of coreCEPs packed in a CiliumEndpointSlice
        :param pulumi.Input[_builtins.str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param pulumi.Input[_builtins.str] namespace: Namespace indicate as CiliumEndpointSlice namespace.
               All the CiliumEndpoints within the same namespace are put together
               in CiliumEndpointSlice.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[CiliumEndpointSliceInitArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        CiliumEndpointSlice contains a group of CoreCiliumendpoints.


        :param str resource_name: The name of the resource.
        :param CiliumEndpointSliceInitArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CiliumEndpointSliceInitArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 endpoints: pulumi.Input[Optional[Sequence[pulumi.Input[Union['CiliumEndpointSliceEndpointsArgs', 'CiliumEndpointSliceEndpointsArgsDict']]]]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional[Union['_meta.v1.ObjectMetaArgs', '_meta.v1.ObjectMetaArgsDict']]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CiliumEndpointSliceInitArgs.__new__(CiliumEndpointSliceInitArgs)

            __props__.__dict__["api_version"] = 'cilium.io/v2alpha1'
            __props__.__dict__["endpoints"] = endpoints
            __props__.__dict__["kind"] = 'CiliumEndpointSlice'
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["namespace"] = namespace
        super(CiliumEndpointSlice, __self__).__init__(
            'kubernetes:cilium.io/v2alpha1:CiliumEndpointSlice',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'CiliumEndpointSlice':
        """
        Get an existing CiliumEndpointSlice resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = CiliumEndpointSliceInitArgs.__new__(CiliumEndpointSliceInitArgs)

        __props__.__dict__["api_version"] = None
        __props__.__dict__["endpoints"] = None
        __props__.__dict__["kind"] = None
        __props__.__dict__["metadata"] = None
        __props__.__dict__["namespace"] = None
        return CiliumEndpointSlice(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Output[_builtins.str]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Output[Sequence['outputs.CiliumEndpointSliceEndpoints']]:
        """
        Endpoints is a list of coreCEPs packed in a CiliumEndpointSlice
        """
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Output[_builtins.str]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['_meta.v1.outputs.ObjectMeta']:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Output[_builtins.str]:
        """
        Namespace indicate as CiliumEndpointSlice namespace.
        All the CiliumEndpoints within the same namespace are put together
        in CiliumEndpointSlice.
        """
        return pulumi.get(self, "namespace")

