# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ... import meta as _meta

__all__ = [
    'AcceleratorFunction',
    'AcceleratorFunctionSpec',
    'AcceleratorFunctionSpecPatch',
    'FpgaRegion',
    'FpgaRegionSpec',
    'FpgaRegionSpecPatch',
]

@pulumi.output_type
class AcceleratorFunction(dict):
    """
    AcceleratorFunction is a specification for an Accelerator Function resource
    provided by a FPGA-based programmable hardware accelerator.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "apiVersion":
            suggest = "api_version"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AcceleratorFunction. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AcceleratorFunction.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AcceleratorFunction.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 api_version: Optional[_builtins.str] = None,
                 kind: Optional[_builtins.str] = None,
                 metadata: Optional['_meta.v1.outputs.ObjectMeta'] = None,
                 spec: Optional['outputs.AcceleratorFunctionSpec'] = None,
                 status: Optional[Mapping[str, _builtins.str]] = None):
        """
        AcceleratorFunction is a specification for an Accelerator Function resource
        provided by a FPGA-based programmable hardware accelerator.
        :param _builtins.str api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param _builtins.str kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param '_meta.v1.ObjectMetaArgs' metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param Mapping[str, _builtins.str] status: AcceleratorFunctionStatus is an empty object used to satisfy operator-sdk.
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'fpga.intel.com/v2')
        if kind is not None:
            pulumi.set(__self__, "kind", 'AcceleratorFunction')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> Optional[_builtins.str]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> Optional[_builtins.str]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional['_meta.v1.outputs.ObjectMeta']:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def spec(self) -> Optional['outputs.AcceleratorFunctionSpec']:
        return pulumi.get(self, "spec")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        AcceleratorFunctionStatus is an empty object used to satisfy operator-sdk.
        """
        return pulumi.get(self, "status")


@pulumi.output_type
class AcceleratorFunctionSpec(dict):
    """
    AcceleratorFunctionSpec contains actual specs for AcceleratorFunction.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "afuId":
            suggest = "afu_id"
        elif key == "interfaceId":
            suggest = "interface_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AcceleratorFunctionSpec. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AcceleratorFunctionSpec.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AcceleratorFunctionSpec.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 afu_id: Optional[_builtins.str] = None,
                 interface_id: Optional[_builtins.str] = None,
                 mode: Optional[_builtins.str] = None):
        """
        AcceleratorFunctionSpec contains actual specs for AcceleratorFunction.
        """
        if afu_id is not None:
            pulumi.set(__self__, "afu_id", afu_id)
        if interface_id is not None:
            pulumi.set(__self__, "interface_id", interface_id)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)

    @_builtins.property
    @pulumi.getter(name="afuId")
    def afu_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "afu_id")

    @_builtins.property
    @pulumi.getter(name="interfaceId")
    def interface_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "interface_id")

    @_builtins.property
    @pulumi.getter
    def mode(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "mode")


@pulumi.output_type
class AcceleratorFunctionSpecPatch(dict):
    """
    AcceleratorFunctionSpec contains actual specs for AcceleratorFunction.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "afuId":
            suggest = "afu_id"
        elif key == "interfaceId":
            suggest = "interface_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AcceleratorFunctionSpecPatch. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AcceleratorFunctionSpecPatch.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AcceleratorFunctionSpecPatch.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 afu_id: Optional[_builtins.str] = None,
                 interface_id: Optional[_builtins.str] = None,
                 mode: Optional[_builtins.str] = None):
        """
        AcceleratorFunctionSpec contains actual specs for AcceleratorFunction.
        """
        if afu_id is not None:
            pulumi.set(__self__, "afu_id", afu_id)
        if interface_id is not None:
            pulumi.set(__self__, "interface_id", interface_id)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)

    @_builtins.property
    @pulumi.getter(name="afuId")
    def afu_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "afu_id")

    @_builtins.property
    @pulumi.getter(name="interfaceId")
    def interface_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "interface_id")

    @_builtins.property
    @pulumi.getter
    def mode(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "mode")


@pulumi.output_type
class FpgaRegion(dict):
    """
    FpgaRegion is a specification for a FPGA region resource which can be programmed
    with a bitstream.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "apiVersion":
            suggest = "api_version"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in FpgaRegion. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        FpgaRegion.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        FpgaRegion.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 api_version: Optional[_builtins.str] = None,
                 kind: Optional[_builtins.str] = None,
                 metadata: Optional['_meta.v1.outputs.ObjectMeta'] = None,
                 spec: Optional['outputs.FpgaRegionSpec'] = None,
                 status: Optional[Mapping[str, _builtins.str]] = None):
        """
        FpgaRegion is a specification for a FPGA region resource which can be programmed
        with a bitstream.
        :param _builtins.str api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param _builtins.str kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param '_meta.v1.ObjectMetaArgs' metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param Mapping[str, _builtins.str] status: FpgaRegionStatus is an empty object used to satisfy operator-sdk.
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'fpga.intel.com/v2')
        if kind is not None:
            pulumi.set(__self__, "kind", 'FpgaRegion')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> Optional[_builtins.str]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> Optional[_builtins.str]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional['_meta.v1.outputs.ObjectMeta']:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def spec(self) -> Optional['outputs.FpgaRegionSpec']:
        return pulumi.get(self, "spec")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        FpgaRegionStatus is an empty object used to satisfy operator-sdk.
        """
        return pulumi.get(self, "status")


@pulumi.output_type
class FpgaRegionSpec(dict):
    """
    FpgaRegionSpec contains actual specs for FpgaRegion.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "interfaceId":
            suggest = "interface_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in FpgaRegionSpec. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        FpgaRegionSpec.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        FpgaRegionSpec.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 interface_id: Optional[_builtins.str] = None):
        """
        FpgaRegionSpec contains actual specs for FpgaRegion.
        """
        if interface_id is not None:
            pulumi.set(__self__, "interface_id", interface_id)

    @_builtins.property
    @pulumi.getter(name="interfaceId")
    def interface_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "interface_id")


@pulumi.output_type
class FpgaRegionSpecPatch(dict):
    """
    FpgaRegionSpec contains actual specs for FpgaRegion.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "interfaceId":
            suggest = "interface_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in FpgaRegionSpecPatch. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        FpgaRegionSpecPatch.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        FpgaRegionSpecPatch.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 interface_id: Optional[_builtins.str] = None):
        """
        FpgaRegionSpec contains actual specs for FpgaRegion.
        """
        if interface_id is not None:
            pulumi.set(__self__, "interface_id", interface_id)

    @_builtins.property
    @pulumi.getter(name="interfaceId")
    def interface_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "interface_id")


