# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AccountArgs', 'Account']

@pulumi.input_type
class AccountArgs:
    def __init__(__self__, *,
                 password: pulumi.Input[_builtins.str],
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 network_id: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 tunnel_medium_type: pulumi.Input[Optional[_builtins.float]] = None,
                 tunnel_type: pulumi.Input[Optional[_builtins.float]] = None,
                 vlan: pulumi.Input[Optional[_builtins.float]] = None):
        """
        The set of arguments for constructing a Account resource.

        :param pulumi.Input[_builtins.str] password: The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
        :param pulumi.Input[_builtins.str] name: The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
        :param pulumi.Input[_builtins.str] network_id: The ID of a UniFi network configuration (the controller's <span pulumi-lang-nodejs="`networkconfId`" pulumi-lang-dotnet="`NetworkconfId`" pulumi-lang-go="`networkconfId`" pulumi-lang-python="`networkconf_id`" pulumi-lang-yaml="`networkconfId`" pulumi-lang-java="`networkconfId`" pulumi-lang-hcl="`networkconf_id`">`networkconfId`</span>) to associate with this account. This is a reference to a network object and is distinct from the <span pulumi-lang-nodejs="`vlan`" pulumi-lang-dotnet="`Vlan`" pulumi-lang-go="`vlan`" pulumi-lang-python="`vlan`" pulumi-lang-yaml="`vlan`" pulumi-lang-java="`vlan`" pulumi-lang-hcl="`vlan`">`vlan`</span> attribute, which sets the 802.1Q VLAN ID delivered via RADIUS.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.float] tunnel_medium_type: The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
                 * <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span> - 802 (includes Ethernet, Token Ring, FDDI) (default)
                 * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - IPv4
                 * <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span> - IPv6
               
               Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span>.
        :param pulumi.Input[_builtins.float] tunnel_type: The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
                 * <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span> - VLAN (default)
                 * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - Point-to-Point Protocol (PPTP)
                 * <span pulumi-lang-nodejs="`9`" pulumi-lang-dotnet="`9`" pulumi-lang-go="`9`" pulumi-lang-python="`9`" pulumi-lang-yaml="`9`" pulumi-lang-java="`9`" pulumi-lang-hcl="`9`">`9`</span> - Point-to-Point Protocol (L2TP)
               
               Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span>.
        :param pulumi.Input[_builtins.float] vlan: The 802.1Q VLAN ID to assign to clients authenticating with this account, used for RADIUS dynamic VLAN assignment. It is delivered together with the tunnel attributes (<span pulumi-lang-nodejs="`tunnelType`" pulumi-lang-dotnet="`TunnelType`" pulumi-lang-go="`tunnelType`" pulumi-lang-python="`tunnel_type`" pulumi-lang-yaml="`tunnelType`" pulumi-lang-java="`tunnelType`" pulumi-lang-hcl="`tunnel_type`">`tunnelType`</span>/<span pulumi-lang-nodejs="`tunnelMediumType`" pulumi-lang-dotnet="`TunnelMediumType`" pulumi-lang-go="`tunnelMediumType`" pulumi-lang-python="`tunnel_medium_type`" pulumi-lang-yaml="`tunnelMediumType`" pulumi-lang-java="`tunnelMediumType`" pulumi-lang-hcl="`tunnel_medium_type`">`tunnelMediumType`</span>). Omitting this attribute means no VLAN is assigned; if a VLAN was set out-of-band (e.g. in the controller UI), omitting it here removes it on the next apply.
        """
        pulumi.set(__self__, "password", password)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if network_id is not None:
            pulumi.set(__self__, "network_id", network_id)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if tunnel_medium_type is not None:
            pulumi.set(__self__, "tunnel_medium_type", tunnel_medium_type)
        if tunnel_type is not None:
            pulumi.set(__self__, "tunnel_type", tunnel_type)
        if vlan is not None:
            pulumi.set(__self__, "vlan", vlan)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[_builtins.str]:
        """
        The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="networkId")
    def network_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of a UniFi network configuration (the controller's <span pulumi-lang-nodejs="`networkconfId`" pulumi-lang-dotnet="`NetworkconfId`" pulumi-lang-go="`networkconfId`" pulumi-lang-python="`networkconf_id`" pulumi-lang-yaml="`networkconfId`" pulumi-lang-java="`networkconfId`" pulumi-lang-hcl="`networkconf_id`">`networkconfId`</span>) to associate with this account. This is a reference to a network object and is distinct from the <span pulumi-lang-nodejs="`vlan`" pulumi-lang-dotnet="`Vlan`" pulumi-lang-go="`vlan`" pulumi-lang-python="`vlan`" pulumi-lang-yaml="`vlan`" pulumi-lang-java="`vlan`" pulumi-lang-hcl="`vlan`">`vlan`</span> attribute, which sets the 802.1Q VLAN ID delivered via RADIUS.
        """
        return pulumi.get(self, "network_id")

    @network_id.setter
    def network_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "network_id", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="tunnelMediumType")
    def tunnel_medium_type(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
          * <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span> - 802 (includes Ethernet, Token Ring, FDDI) (default)
          * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - IPv4
          * <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span> - IPv6

        Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span>.
        """
        return pulumi.get(self, "tunnel_medium_type")

    @tunnel_medium_type.setter
    def tunnel_medium_type(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "tunnel_medium_type", value)

    @_builtins.property
    @pulumi.getter(name="tunnelType")
    def tunnel_type(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
          * <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span> - VLAN (default)
          * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - Point-to-Point Protocol (PPTP)
          * <span pulumi-lang-nodejs="`9`" pulumi-lang-dotnet="`9`" pulumi-lang-go="`9`" pulumi-lang-python="`9`" pulumi-lang-yaml="`9`" pulumi-lang-java="`9`" pulumi-lang-hcl="`9`">`9`</span> - Point-to-Point Protocol (L2TP)

        Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span>.
        """
        return pulumi.get(self, "tunnel_type")

    @tunnel_type.setter
    def tunnel_type(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "tunnel_type", value)

    @_builtins.property
    @pulumi.getter
    def vlan(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The 802.1Q VLAN ID to assign to clients authenticating with this account, used for RADIUS dynamic VLAN assignment. It is delivered together with the tunnel attributes (<span pulumi-lang-nodejs="`tunnelType`" pulumi-lang-dotnet="`TunnelType`" pulumi-lang-go="`tunnelType`" pulumi-lang-python="`tunnel_type`" pulumi-lang-yaml="`tunnelType`" pulumi-lang-java="`tunnelType`" pulumi-lang-hcl="`tunnel_type`">`tunnelType`</span>/<span pulumi-lang-nodejs="`tunnelMediumType`" pulumi-lang-dotnet="`TunnelMediumType`" pulumi-lang-go="`tunnelMediumType`" pulumi-lang-python="`tunnel_medium_type`" pulumi-lang-yaml="`tunnelMediumType`" pulumi-lang-java="`tunnelMediumType`" pulumi-lang-hcl="`tunnel_medium_type`">`tunnelMediumType`</span>). Omitting this attribute means no VLAN is assigned; if a VLAN was set out-of-band (e.g. in the controller UI), omitting it here removes it on the next apply.
        """
        return pulumi.get(self, "vlan")

    @vlan.setter
    def vlan(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "vlan", value)


@pulumi.input_type
class _AccountState:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 network_id: pulumi.Input[Optional[_builtins.str]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 tunnel_medium_type: pulumi.Input[Optional[_builtins.float]] = None,
                 tunnel_type: pulumi.Input[Optional[_builtins.float]] = None,
                 vlan: pulumi.Input[Optional[_builtins.float]] = None):
        """
        Input properties used for looking up and filtering Account resources.

        :param pulumi.Input[_builtins.str] name: The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
        :param pulumi.Input[_builtins.str] network_id: The ID of a UniFi network configuration (the controller's <span pulumi-lang-nodejs="`networkconfId`" pulumi-lang-dotnet="`NetworkconfId`" pulumi-lang-go="`networkconfId`" pulumi-lang-python="`networkconf_id`" pulumi-lang-yaml="`networkconfId`" pulumi-lang-java="`networkconfId`" pulumi-lang-hcl="`networkconf_id`">`networkconfId`</span>) to associate with this account. This is a reference to a network object and is distinct from the <span pulumi-lang-nodejs="`vlan`" pulumi-lang-dotnet="`Vlan`" pulumi-lang-go="`vlan`" pulumi-lang-python="`vlan`" pulumi-lang-yaml="`vlan`" pulumi-lang-java="`vlan`" pulumi-lang-hcl="`vlan`">`vlan`</span> attribute, which sets the 802.1Q VLAN ID delivered via RADIUS.
        :param pulumi.Input[_builtins.str] password: The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.float] tunnel_medium_type: The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
                 * <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span> - 802 (includes Ethernet, Token Ring, FDDI) (default)
                 * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - IPv4
                 * <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span> - IPv6
               
               Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span>.
        :param pulumi.Input[_builtins.float] tunnel_type: The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
                 * <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span> - VLAN (default)
                 * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - Point-to-Point Protocol (PPTP)
                 * <span pulumi-lang-nodejs="`9`" pulumi-lang-dotnet="`9`" pulumi-lang-go="`9`" pulumi-lang-python="`9`" pulumi-lang-yaml="`9`" pulumi-lang-java="`9`" pulumi-lang-hcl="`9`">`9`</span> - Point-to-Point Protocol (L2TP)
               
               Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span>.
        :param pulumi.Input[_builtins.float] vlan: The 802.1Q VLAN ID to assign to clients authenticating with this account, used for RADIUS dynamic VLAN assignment. It is delivered together with the tunnel attributes (<span pulumi-lang-nodejs="`tunnelType`" pulumi-lang-dotnet="`TunnelType`" pulumi-lang-go="`tunnelType`" pulumi-lang-python="`tunnel_type`" pulumi-lang-yaml="`tunnelType`" pulumi-lang-java="`tunnelType`" pulumi-lang-hcl="`tunnel_type`">`tunnelType`</span>/<span pulumi-lang-nodejs="`tunnelMediumType`" pulumi-lang-dotnet="`TunnelMediumType`" pulumi-lang-go="`tunnelMediumType`" pulumi-lang-python="`tunnel_medium_type`" pulumi-lang-yaml="`tunnelMediumType`" pulumi-lang-java="`tunnelMediumType`" pulumi-lang-hcl="`tunnel_medium_type`">`tunnelMediumType`</span>). Omitting this attribute means no VLAN is assigned; if a VLAN was set out-of-band (e.g. in the controller UI), omitting it here removes it on the next apply.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if network_id is not None:
            pulumi.set(__self__, "network_id", network_id)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if tunnel_medium_type is not None:
            pulumi.set(__self__, "tunnel_medium_type", tunnel_medium_type)
        if tunnel_type is not None:
            pulumi.set(__self__, "tunnel_type", tunnel_type)
        if vlan is not None:
            pulumi.set(__self__, "vlan", vlan)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="networkId")
    def network_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of a UniFi network configuration (the controller's <span pulumi-lang-nodejs="`networkconfId`" pulumi-lang-dotnet="`NetworkconfId`" pulumi-lang-go="`networkconfId`" pulumi-lang-python="`networkconf_id`" pulumi-lang-yaml="`networkconfId`" pulumi-lang-java="`networkconfId`" pulumi-lang-hcl="`networkconf_id`">`networkconfId`</span>) to associate with this account. This is a reference to a network object and is distinct from the <span pulumi-lang-nodejs="`vlan`" pulumi-lang-dotnet="`Vlan`" pulumi-lang-go="`vlan`" pulumi-lang-python="`vlan`" pulumi-lang-yaml="`vlan`" pulumi-lang-java="`vlan`" pulumi-lang-hcl="`vlan`">`vlan`</span> attribute, which sets the 802.1Q VLAN ID delivered via RADIUS.
        """
        return pulumi.get(self, "network_id")

    @network_id.setter
    def network_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "network_id", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="tunnelMediumType")
    def tunnel_medium_type(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
          * <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span> - 802 (includes Ethernet, Token Ring, FDDI) (default)
          * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - IPv4
          * <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span> - IPv6

        Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span>.
        """
        return pulumi.get(self, "tunnel_medium_type")

    @tunnel_medium_type.setter
    def tunnel_medium_type(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "tunnel_medium_type", value)

    @_builtins.property
    @pulumi.getter(name="tunnelType")
    def tunnel_type(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
          * <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span> - VLAN (default)
          * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - Point-to-Point Protocol (PPTP)
          * <span pulumi-lang-nodejs="`9`" pulumi-lang-dotnet="`9`" pulumi-lang-go="`9`" pulumi-lang-python="`9`" pulumi-lang-yaml="`9`" pulumi-lang-java="`9`" pulumi-lang-hcl="`9`">`9`</span> - Point-to-Point Protocol (L2TP)

        Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span>.
        """
        return pulumi.get(self, "tunnel_type")

    @tunnel_type.setter
    def tunnel_type(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "tunnel_type", value)

    @_builtins.property
    @pulumi.getter
    def vlan(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The 802.1Q VLAN ID to assign to clients authenticating with this account, used for RADIUS dynamic VLAN assignment. It is delivered together with the tunnel attributes (<span pulumi-lang-nodejs="`tunnelType`" pulumi-lang-dotnet="`TunnelType`" pulumi-lang-go="`tunnelType`" pulumi-lang-python="`tunnel_type`" pulumi-lang-yaml="`tunnelType`" pulumi-lang-java="`tunnelType`" pulumi-lang-hcl="`tunnel_type`">`tunnelType`</span>/<span pulumi-lang-nodejs="`tunnelMediumType`" pulumi-lang-dotnet="`TunnelMediumType`" pulumi-lang-go="`tunnelMediumType`" pulumi-lang-python="`tunnel_medium_type`" pulumi-lang-yaml="`tunnelMediumType`" pulumi-lang-java="`tunnelMediumType`" pulumi-lang-hcl="`tunnel_medium_type`">`tunnelMediumType`</span>). Omitting this attribute means no VLAN is assigned; if a VLAN was set out-of-band (e.g. in the controller UI), omitting it here removes it on the next apply.
        """
        return pulumi.get(self, "vlan")

    @vlan.setter
    def vlan(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "vlan", value)


@pulumi.type_token("unifi:index/account:Account")
class Account(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 network_id: pulumi.Input[Optional[_builtins.str]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 tunnel_medium_type: pulumi.Input[Optional[_builtins.float]] = None,
                 tunnel_type: pulumi.Input[Optional[_builtins.float]] = None,
                 vlan: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        """
        Create a Account resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
        :param pulumi.Input[_builtins.str] network_id: The ID of a UniFi network configuration (the controller's <span pulumi-lang-nodejs="`networkconfId`" pulumi-lang-dotnet="`NetworkconfId`" pulumi-lang-go="`networkconfId`" pulumi-lang-python="`networkconf_id`" pulumi-lang-yaml="`networkconfId`" pulumi-lang-java="`networkconfId`" pulumi-lang-hcl="`networkconf_id`">`networkconfId`</span>) to associate with this account. This is a reference to a network object and is distinct from the <span pulumi-lang-nodejs="`vlan`" pulumi-lang-dotnet="`Vlan`" pulumi-lang-go="`vlan`" pulumi-lang-python="`vlan`" pulumi-lang-yaml="`vlan`" pulumi-lang-java="`vlan`" pulumi-lang-hcl="`vlan`">`vlan`</span> attribute, which sets the 802.1Q VLAN ID delivered via RADIUS.
        :param pulumi.Input[_builtins.str] password: The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.float] tunnel_medium_type: The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
                 * <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span> - 802 (includes Ethernet, Token Ring, FDDI) (default)
                 * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - IPv4
                 * <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span> - IPv6
               
               Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span>.
        :param pulumi.Input[_builtins.float] tunnel_type: The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
                 * <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span> - VLAN (default)
                 * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - Point-to-Point Protocol (PPTP)
                 * <span pulumi-lang-nodejs="`9`" pulumi-lang-dotnet="`9`" pulumi-lang-go="`9`" pulumi-lang-python="`9`" pulumi-lang-yaml="`9`" pulumi-lang-java="`9`" pulumi-lang-hcl="`9`">`9`</span> - Point-to-Point Protocol (L2TP)
               
               Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span>.
        :param pulumi.Input[_builtins.float] vlan: The 802.1Q VLAN ID to assign to clients authenticating with this account, used for RADIUS dynamic VLAN assignment. It is delivered together with the tunnel attributes (<span pulumi-lang-nodejs="`tunnelType`" pulumi-lang-dotnet="`TunnelType`" pulumi-lang-go="`tunnelType`" pulumi-lang-python="`tunnel_type`" pulumi-lang-yaml="`tunnelType`" pulumi-lang-java="`tunnelType`" pulumi-lang-hcl="`tunnel_type`">`tunnelType`</span>/<span pulumi-lang-nodejs="`tunnelMediumType`" pulumi-lang-dotnet="`TunnelMediumType`" pulumi-lang-go="`tunnelMediumType`" pulumi-lang-python="`tunnel_medium_type`" pulumi-lang-yaml="`tunnelMediumType`" pulumi-lang-java="`tunnelMediumType`" pulumi-lang-hcl="`tunnel_medium_type`">`tunnelMediumType`</span>). Omitting this attribute means no VLAN is assigned; if a VLAN was set out-of-band (e.g. in the controller UI), omitting it here removes it on the next apply.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AccountArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Account resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AccountArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AccountArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 network_id: pulumi.Input[Optional[_builtins.str]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 tunnel_medium_type: pulumi.Input[Optional[_builtins.float]] = None,
                 tunnel_type: pulumi.Input[Optional[_builtins.float]] = None,
                 vlan: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AccountArgs.__new__(AccountArgs)

            __props__.__dict__["name"] = name
            __props__.__dict__["network_id"] = network_id
            if password is None and not opts.urn:
                raise TypeError("Missing required property 'password'")
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["site"] = site
            __props__.__dict__["tunnel_medium_type"] = tunnel_medium_type
            __props__.__dict__["tunnel_type"] = tunnel_type
            __props__.__dict__["vlan"] = vlan
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["password"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Account, __self__).__init__(
            'unifi:index/account:Account',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            network_id: pulumi.Input[Optional[_builtins.str]] = None,
            password: pulumi.Input[Optional[_builtins.str]] = None,
            site: pulumi.Input[Optional[_builtins.str]] = None,
            tunnel_medium_type: pulumi.Input[Optional[_builtins.float]] = None,
            tunnel_type: pulumi.Input[Optional[_builtins.float]] = None,
            vlan: pulumi.Input[Optional[_builtins.float]] = None) -> 'Account':
        """
        Get an existing Account resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
        :param pulumi.Input[_builtins.str] network_id: The ID of a UniFi network configuration (the controller's <span pulumi-lang-nodejs="`networkconfId`" pulumi-lang-dotnet="`NetworkconfId`" pulumi-lang-go="`networkconfId`" pulumi-lang-python="`networkconf_id`" pulumi-lang-yaml="`networkconfId`" pulumi-lang-java="`networkconfId`" pulumi-lang-hcl="`networkconf_id`">`networkconfId`</span>) to associate with this account. This is a reference to a network object and is distinct from the <span pulumi-lang-nodejs="`vlan`" pulumi-lang-dotnet="`Vlan`" pulumi-lang-go="`vlan`" pulumi-lang-python="`vlan`" pulumi-lang-yaml="`vlan`" pulumi-lang-java="`vlan`" pulumi-lang-hcl="`vlan`">`vlan`</span> attribute, which sets the 802.1Q VLAN ID delivered via RADIUS.
        :param pulumi.Input[_builtins.str] password: The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.float] tunnel_medium_type: The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
                 * <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span> - 802 (includes Ethernet, Token Ring, FDDI) (default)
                 * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - IPv4
                 * <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span> - IPv6
               
               Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span>.
        :param pulumi.Input[_builtins.float] tunnel_type: The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
                 * <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span> - VLAN (default)
                 * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - Point-to-Point Protocol (PPTP)
                 * <span pulumi-lang-nodejs="`9`" pulumi-lang-dotnet="`9`" pulumi-lang-go="`9`" pulumi-lang-python="`9`" pulumi-lang-yaml="`9`" pulumi-lang-java="`9`" pulumi-lang-hcl="`9`">`9`</span> - Point-to-Point Protocol (L2TP)
               
               Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span>.
        :param pulumi.Input[_builtins.float] vlan: The 802.1Q VLAN ID to assign to clients authenticating with this account, used for RADIUS dynamic VLAN assignment. It is delivered together with the tunnel attributes (<span pulumi-lang-nodejs="`tunnelType`" pulumi-lang-dotnet="`TunnelType`" pulumi-lang-go="`tunnelType`" pulumi-lang-python="`tunnel_type`" pulumi-lang-yaml="`tunnelType`" pulumi-lang-java="`tunnelType`" pulumi-lang-hcl="`tunnel_type`">`tunnelType`</span>/<span pulumi-lang-nodejs="`tunnelMediumType`" pulumi-lang-dotnet="`TunnelMediumType`" pulumi-lang-go="`tunnelMediumType`" pulumi-lang-python="`tunnel_medium_type`" pulumi-lang-yaml="`tunnelMediumType`" pulumi-lang-java="`tunnelMediumType`" pulumi-lang-hcl="`tunnel_medium_type`">`tunnelMediumType`</span>). Omitting this attribute means no VLAN is assigned; if a VLAN was set out-of-band (e.g. in the controller UI), omitting it here removes it on the next apply.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AccountState.__new__(_AccountState)

        __props__.__dict__["name"] = name
        __props__.__dict__["network_id"] = network_id
        __props__.__dict__["password"] = password
        __props__.__dict__["site"] = site
        __props__.__dict__["tunnel_medium_type"] = tunnel_medium_type
        __props__.__dict__["tunnel_type"] = tunnel_type
        __props__.__dict__["vlan"] = vlan
        return Account(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="networkId")
    def network_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The ID of a UniFi network configuration (the controller's <span pulumi-lang-nodejs="`networkconfId`" pulumi-lang-dotnet="`NetworkconfId`" pulumi-lang-go="`networkconfId`" pulumi-lang-python="`networkconf_id`" pulumi-lang-yaml="`networkconfId`" pulumi-lang-java="`networkconfId`" pulumi-lang-hcl="`networkconf_id`">`networkconfId`</span>) to associate with this account. This is a reference to a network object and is distinct from the <span pulumi-lang-nodejs="`vlan`" pulumi-lang-dotnet="`Vlan`" pulumi-lang-go="`vlan`" pulumi-lang-python="`vlan`" pulumi-lang-yaml="`vlan`" pulumi-lang-java="`vlan`" pulumi-lang-hcl="`vlan`">`vlan`</span> attribute, which sets the 802.1Q VLAN ID delivered via RADIUS.
        """
        return pulumi.get(self, "network_id")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[_builtins.str]:
        """
        The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @_builtins.property
    @pulumi.getter(name="tunnelMediumType")
    def tunnel_medium_type(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
          * <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span> - 802 (includes Ethernet, Token Ring, FDDI) (default)
          * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - IPv4
          * <span pulumi-lang-nodejs="`2`" pulumi-lang-dotnet="`2`" pulumi-lang-go="`2`" pulumi-lang-python="`2`" pulumi-lang-yaml="`2`" pulumi-lang-java="`2`" pulumi-lang-hcl="`2`">`2`</span> - IPv6

        Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`6`" pulumi-lang-dotnet="`6`" pulumi-lang-go="`6`" pulumi-lang-python="`6`" pulumi-lang-yaml="`6`" pulumi-lang-java="`6`" pulumi-lang-hcl="`6`">`6`</span>.
        """
        return pulumi.get(self, "tunnel_medium_type")

    @_builtins.property
    @pulumi.getter(name="tunnelType")
    def tunnel_type(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
          * <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span> - VLAN (default)
          * <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span> - Point-to-Point Protocol (PPTP)
          * <span pulumi-lang-nodejs="`9`" pulumi-lang-dotnet="`9`" pulumi-lang-go="`9`" pulumi-lang-python="`9`" pulumi-lang-yaml="`9`" pulumi-lang-java="`9`" pulumi-lang-hcl="`9`">`9`</span> - Point-to-Point Protocol (L2TP)

        Only change this if you need specific tunneling behavior. Defaults to <span pulumi-lang-nodejs="`13`" pulumi-lang-dotnet="`13`" pulumi-lang-go="`13`" pulumi-lang-python="`13`" pulumi-lang-yaml="`13`" pulumi-lang-java="`13`" pulumi-lang-hcl="`13`">`13`</span>.
        """
        return pulumi.get(self, "tunnel_type")

    @_builtins.property
    @pulumi.getter
    def vlan(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The 802.1Q VLAN ID to assign to clients authenticating with this account, used for RADIUS dynamic VLAN assignment. It is delivered together with the tunnel attributes (<span pulumi-lang-nodejs="`tunnelType`" pulumi-lang-dotnet="`TunnelType`" pulumi-lang-go="`tunnelType`" pulumi-lang-python="`tunnel_type`" pulumi-lang-yaml="`tunnelType`" pulumi-lang-java="`tunnelType`" pulumi-lang-hcl="`tunnel_type`">`tunnelType`</span>/<span pulumi-lang-nodejs="`tunnelMediumType`" pulumi-lang-dotnet="`TunnelMediumType`" pulumi-lang-go="`tunnelMediumType`" pulumi-lang-python="`tunnel_medium_type`" pulumi-lang-yaml="`tunnelMediumType`" pulumi-lang-java="`tunnelMediumType`" pulumi-lang-hcl="`tunnel_medium_type`">`tunnelMediumType`</span>). Omitting this attribute means no VLAN is assigned; if a VLAN was set out-of-band (e.g. in the controller UI), omitting it here removes it on the next apply.
        """
        return pulumi.get(self, "vlan")

