# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SettingRadiusArgs', 'SettingRadius']

@pulumi.input_type
class SettingRadiusArgs:
    def __init__(__self__, *,
                 accounting_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 accounting_port: pulumi.Input[Optional[_builtins.float]] = None,
                 auth_port: pulumi.Input[Optional[_builtins.float]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 interim_update_interval: pulumi.Input[Optional[_builtins.float]] = None,
                 secret: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 tunneled_reply: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a SettingRadius resource.

        :param pulumi.Input[_builtins.bool] accounting_enabled: Enable RADIUS accounting to track user sessions, including connection time, data usage, and other metrics. This information can be useful for billing, capacity planning, and security auditing. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        :param pulumi.Input[_builtins.float] accounting_port: The UDP port number for RADIUS accounting communications. The standard port is 1813. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1813`" pulumi-lang-dotnet="`1813`" pulumi-lang-go="`1813`" pulumi-lang-python="`1813`" pulumi-lang-yaml="`1813`" pulumi-lang-java="`1813`" pulumi-lang-hcl="`1813`">`1813`</span>.
        :param pulumi.Input[_builtins.float] auth_port: The UDP port number for RADIUS authentication communications. The standard port is 1812. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1812`" pulumi-lang-dotnet="`1812`" pulumi-lang-go="`1812`" pulumi-lang-python="`1812`" pulumi-lang-yaml="`1812`" pulumi-lang-java="`1812`" pulumi-lang-hcl="`1812`">`1812`</span>.
        :param pulumi.Input[_builtins.bool] enabled: Enable or disable the built-in RADIUS server. When disabled, no RADIUS authentication or accounting services will be provided, affecting any network services that rely on RADIUS (like WPA2-Enterprise networks). Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        :param pulumi.Input[_builtins.float] interim_update_interval: The interval (in seconds) at which the RADIUS server collects and updates statistics from connected clients. Default is 3600 seconds (1 hour). Lower values provide more frequent updates but increase server load. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`" pulumi-lang-hcl="`3600`">`3600`</span>.
        :param pulumi.Input[_builtins.str] secret: The shared secret passphrase used to authenticate RADIUS clients (like wireless access points) with the RADIUS server. This should be a strong, random string known only to the server and its clients. Defaults to ``.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where these RADIUS settings should be applied. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.bool] tunneled_reply: Enable encrypted communication between the RADIUS server and clients using RADIUS tunneling. This adds an extra layer of security by protecting RADIUS attributes in transit. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        if accounting_enabled is not None:
            pulumi.set(__self__, "accounting_enabled", accounting_enabled)
        if accounting_port is not None:
            pulumi.set(__self__, "accounting_port", accounting_port)
        if auth_port is not None:
            pulumi.set(__self__, "auth_port", auth_port)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if interim_update_interval is not None:
            pulumi.set(__self__, "interim_update_interval", interim_update_interval)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if tunneled_reply is not None:
            pulumi.set(__self__, "tunneled_reply", tunneled_reply)

    @_builtins.property
    @pulumi.getter(name="accountingEnabled")
    def accounting_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable RADIUS accounting to track user sessions, including connection time, data usage, and other metrics. This information can be useful for billing, capacity planning, and security auditing. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        """
        return pulumi.get(self, "accounting_enabled")

    @accounting_enabled.setter
    def accounting_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "accounting_enabled", value)

    @_builtins.property
    @pulumi.getter(name="accountingPort")
    def accounting_port(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The UDP port number for RADIUS accounting communications. The standard port is 1813. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1813`" pulumi-lang-dotnet="`1813`" pulumi-lang-go="`1813`" pulumi-lang-python="`1813`" pulumi-lang-yaml="`1813`" pulumi-lang-java="`1813`" pulumi-lang-hcl="`1813`">`1813`</span>.
        """
        return pulumi.get(self, "accounting_port")

    @accounting_port.setter
    def accounting_port(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "accounting_port", value)

    @_builtins.property
    @pulumi.getter(name="authPort")
    def auth_port(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The UDP port number for RADIUS authentication communications. The standard port is 1812. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1812`" pulumi-lang-dotnet="`1812`" pulumi-lang-go="`1812`" pulumi-lang-python="`1812`" pulumi-lang-yaml="`1812`" pulumi-lang-java="`1812`" pulumi-lang-hcl="`1812`">`1812`</span>.
        """
        return pulumi.get(self, "auth_port")

    @auth_port.setter
    def auth_port(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "auth_port", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable or disable the built-in RADIUS server. When disabled, no RADIUS authentication or accounting services will be provided, affecting any network services that rely on RADIUS (like WPA2-Enterprise networks). Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="interimUpdateInterval")
    def interim_update_interval(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The interval (in seconds) at which the RADIUS server collects and updates statistics from connected clients. Default is 3600 seconds (1 hour). Lower values provide more frequent updates but increase server load. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`" pulumi-lang-hcl="`3600`">`3600`</span>.
        """
        return pulumi.get(self, "interim_update_interval")

    @interim_update_interval.setter
    def interim_update_interval(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "interim_update_interval", value)

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The shared secret passphrase used to authenticate RADIUS clients (like wireless access points) with the RADIUS server. This should be a strong, random string known only to the server and its clients. Defaults to ``.
        """
        return pulumi.get(self, "secret")

    @secret.setter
    def secret(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the UniFi site where these RADIUS settings should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="tunneledReply")
    def tunneled_reply(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable encrypted communication between the RADIUS server and clients using RADIUS tunneling. This adds an extra layer of security by protecting RADIUS attributes in transit. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        return pulumi.get(self, "tunneled_reply")

    @tunneled_reply.setter
    def tunneled_reply(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "tunneled_reply", value)


@pulumi.input_type
class _SettingRadiusState:
    def __init__(__self__, *,
                 accounting_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 accounting_port: pulumi.Input[Optional[_builtins.float]] = None,
                 auth_port: pulumi.Input[Optional[_builtins.float]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 interim_update_interval: pulumi.Input[Optional[_builtins.float]] = None,
                 secret: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 tunneled_reply: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering SettingRadius resources.

        :param pulumi.Input[_builtins.bool] accounting_enabled: Enable RADIUS accounting to track user sessions, including connection time, data usage, and other metrics. This information can be useful for billing, capacity planning, and security auditing. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        :param pulumi.Input[_builtins.float] accounting_port: The UDP port number for RADIUS accounting communications. The standard port is 1813. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1813`" pulumi-lang-dotnet="`1813`" pulumi-lang-go="`1813`" pulumi-lang-python="`1813`" pulumi-lang-yaml="`1813`" pulumi-lang-java="`1813`" pulumi-lang-hcl="`1813`">`1813`</span>.
        :param pulumi.Input[_builtins.float] auth_port: The UDP port number for RADIUS authentication communications. The standard port is 1812. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1812`" pulumi-lang-dotnet="`1812`" pulumi-lang-go="`1812`" pulumi-lang-python="`1812`" pulumi-lang-yaml="`1812`" pulumi-lang-java="`1812`" pulumi-lang-hcl="`1812`">`1812`</span>.
        :param pulumi.Input[_builtins.bool] enabled: Enable or disable the built-in RADIUS server. When disabled, no RADIUS authentication or accounting services will be provided, affecting any network services that rely on RADIUS (like WPA2-Enterprise networks). Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        :param pulumi.Input[_builtins.float] interim_update_interval: The interval (in seconds) at which the RADIUS server collects and updates statistics from connected clients. Default is 3600 seconds (1 hour). Lower values provide more frequent updates but increase server load. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`" pulumi-lang-hcl="`3600`">`3600`</span>.
        :param pulumi.Input[_builtins.str] secret: The shared secret passphrase used to authenticate RADIUS clients (like wireless access points) with the RADIUS server. This should be a strong, random string known only to the server and its clients. Defaults to ``.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where these RADIUS settings should be applied. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.bool] tunneled_reply: Enable encrypted communication between the RADIUS server and clients using RADIUS tunneling. This adds an extra layer of security by protecting RADIUS attributes in transit. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        if accounting_enabled is not None:
            pulumi.set(__self__, "accounting_enabled", accounting_enabled)
        if accounting_port is not None:
            pulumi.set(__self__, "accounting_port", accounting_port)
        if auth_port is not None:
            pulumi.set(__self__, "auth_port", auth_port)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if interim_update_interval is not None:
            pulumi.set(__self__, "interim_update_interval", interim_update_interval)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)
        if site is not None:
            pulumi.set(__self__, "site", site)
        if tunneled_reply is not None:
            pulumi.set(__self__, "tunneled_reply", tunneled_reply)

    @_builtins.property
    @pulumi.getter(name="accountingEnabled")
    def accounting_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable RADIUS accounting to track user sessions, including connection time, data usage, and other metrics. This information can be useful for billing, capacity planning, and security auditing. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        """
        return pulumi.get(self, "accounting_enabled")

    @accounting_enabled.setter
    def accounting_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "accounting_enabled", value)

    @_builtins.property
    @pulumi.getter(name="accountingPort")
    def accounting_port(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The UDP port number for RADIUS accounting communications. The standard port is 1813. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1813`" pulumi-lang-dotnet="`1813`" pulumi-lang-go="`1813`" pulumi-lang-python="`1813`" pulumi-lang-yaml="`1813`" pulumi-lang-java="`1813`" pulumi-lang-hcl="`1813`">`1813`</span>.
        """
        return pulumi.get(self, "accounting_port")

    @accounting_port.setter
    def accounting_port(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "accounting_port", value)

    @_builtins.property
    @pulumi.getter(name="authPort")
    def auth_port(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The UDP port number for RADIUS authentication communications. The standard port is 1812. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1812`" pulumi-lang-dotnet="`1812`" pulumi-lang-go="`1812`" pulumi-lang-python="`1812`" pulumi-lang-yaml="`1812`" pulumi-lang-java="`1812`" pulumi-lang-hcl="`1812`">`1812`</span>.
        """
        return pulumi.get(self, "auth_port")

    @auth_port.setter
    def auth_port(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "auth_port", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable or disable the built-in RADIUS server. When disabled, no RADIUS authentication or accounting services will be provided, affecting any network services that rely on RADIUS (like WPA2-Enterprise networks). Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="interimUpdateInterval")
    def interim_update_interval(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        The interval (in seconds) at which the RADIUS server collects and updates statistics from connected clients. Default is 3600 seconds (1 hour). Lower values provide more frequent updates but increase server load. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`" pulumi-lang-hcl="`3600`">`3600`</span>.
        """
        return pulumi.get(self, "interim_update_interval")

    @interim_update_interval.setter
    def interim_update_interval(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "interim_update_interval", value)

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The shared secret passphrase used to authenticate RADIUS clients (like wireless access points) with the RADIUS server. This should be a strong, random string known only to the server and its clients. Defaults to ``.
        """
        return pulumi.get(self, "secret")

    @secret.setter
    def secret(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the UniFi site where these RADIUS settings should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "site", value)

    @_builtins.property
    @pulumi.getter(name="tunneledReply")
    def tunneled_reply(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable encrypted communication between the RADIUS server and clients using RADIUS tunneling. This adds an extra layer of security by protecting RADIUS attributes in transit. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        return pulumi.get(self, "tunneled_reply")

    @tunneled_reply.setter
    def tunneled_reply(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "tunneled_reply", value)


@pulumi.type_token("unifi:index/settingRadius:SettingRadius")
class SettingRadius(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accounting_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 accounting_port: pulumi.Input[Optional[_builtins.float]] = None,
                 auth_port: pulumi.Input[Optional[_builtins.float]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 interim_update_interval: pulumi.Input[Optional[_builtins.float]] = None,
                 secret: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 tunneled_reply: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a SettingRadius resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] accounting_enabled: Enable RADIUS accounting to track user sessions, including connection time, data usage, and other metrics. This information can be useful for billing, capacity planning, and security auditing. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        :param pulumi.Input[_builtins.float] accounting_port: The UDP port number for RADIUS accounting communications. The standard port is 1813. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1813`" pulumi-lang-dotnet="`1813`" pulumi-lang-go="`1813`" pulumi-lang-python="`1813`" pulumi-lang-yaml="`1813`" pulumi-lang-java="`1813`" pulumi-lang-hcl="`1813`">`1813`</span>.
        :param pulumi.Input[_builtins.float] auth_port: The UDP port number for RADIUS authentication communications. The standard port is 1812. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1812`" pulumi-lang-dotnet="`1812`" pulumi-lang-go="`1812`" pulumi-lang-python="`1812`" pulumi-lang-yaml="`1812`" pulumi-lang-java="`1812`" pulumi-lang-hcl="`1812`">`1812`</span>.
        :param pulumi.Input[_builtins.bool] enabled: Enable or disable the built-in RADIUS server. When disabled, no RADIUS authentication or accounting services will be provided, affecting any network services that rely on RADIUS (like WPA2-Enterprise networks). Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        :param pulumi.Input[_builtins.float] interim_update_interval: The interval (in seconds) at which the RADIUS server collects and updates statistics from connected clients. Default is 3600 seconds (1 hour). Lower values provide more frequent updates but increase server load. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`" pulumi-lang-hcl="`3600`">`3600`</span>.
        :param pulumi.Input[_builtins.str] secret: The shared secret passphrase used to authenticate RADIUS clients (like wireless access points) with the RADIUS server. This should be a strong, random string known only to the server and its clients. Defaults to ``.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where these RADIUS settings should be applied. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.bool] tunneled_reply: Enable encrypted communication between the RADIUS server and clients using RADIUS tunneling. This adds an extra layer of security by protecting RADIUS attributes in transit. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SettingRadiusArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SettingRadius resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SettingRadiusArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SettingRadiusArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accounting_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 accounting_port: pulumi.Input[Optional[_builtins.float]] = None,
                 auth_port: pulumi.Input[Optional[_builtins.float]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 interim_update_interval: pulumi.Input[Optional[_builtins.float]] = None,
                 secret: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 tunneled_reply: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SettingRadiusArgs.__new__(SettingRadiusArgs)

            __props__.__dict__["accounting_enabled"] = accounting_enabled
            __props__.__dict__["accounting_port"] = accounting_port
            __props__.__dict__["auth_port"] = auth_port
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["interim_update_interval"] = interim_update_interval
            __props__.__dict__["secret"] = None if secret is None else pulumi.Output.secret(secret)
            __props__.__dict__["site"] = site
            __props__.__dict__["tunneled_reply"] = tunneled_reply
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["secret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(SettingRadius, __self__).__init__(
            'unifi:index/settingRadius:SettingRadius',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            accounting_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            accounting_port: pulumi.Input[Optional[_builtins.float]] = None,
            auth_port: pulumi.Input[Optional[_builtins.float]] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            interim_update_interval: pulumi.Input[Optional[_builtins.float]] = None,
            secret: pulumi.Input[Optional[_builtins.str]] = None,
            site: pulumi.Input[Optional[_builtins.str]] = None,
            tunneled_reply: pulumi.Input[Optional[_builtins.bool]] = None) -> 'SettingRadius':
        """
        Get an existing SettingRadius resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] accounting_enabled: Enable RADIUS accounting to track user sessions, including connection time, data usage, and other metrics. This information can be useful for billing, capacity planning, and security auditing. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        :param pulumi.Input[_builtins.float] accounting_port: The UDP port number for RADIUS accounting communications. The standard port is 1813. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1813`" pulumi-lang-dotnet="`1813`" pulumi-lang-go="`1813`" pulumi-lang-python="`1813`" pulumi-lang-yaml="`1813`" pulumi-lang-java="`1813`" pulumi-lang-hcl="`1813`">`1813`</span>.
        :param pulumi.Input[_builtins.float] auth_port: The UDP port number for RADIUS authentication communications. The standard port is 1812. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1812`" pulumi-lang-dotnet="`1812`" pulumi-lang-go="`1812`" pulumi-lang-python="`1812`" pulumi-lang-yaml="`1812`" pulumi-lang-java="`1812`" pulumi-lang-hcl="`1812`">`1812`</span>.
        :param pulumi.Input[_builtins.bool] enabled: Enable or disable the built-in RADIUS server. When disabled, no RADIUS authentication or accounting services will be provided, affecting any network services that rely on RADIUS (like WPA2-Enterprise networks). Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        :param pulumi.Input[_builtins.float] interim_update_interval: The interval (in seconds) at which the RADIUS server collects and updates statistics from connected clients. Default is 3600 seconds (1 hour). Lower values provide more frequent updates but increase server load. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`" pulumi-lang-hcl="`3600`">`3600`</span>.
        :param pulumi.Input[_builtins.str] secret: The shared secret passphrase used to authenticate RADIUS clients (like wireless access points) with the RADIUS server. This should be a strong, random string known only to the server and its clients. Defaults to ``.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where these RADIUS settings should be applied. If not specified, the default site will be used.
        :param pulumi.Input[_builtins.bool] tunneled_reply: Enable encrypted communication between the RADIUS server and clients using RADIUS tunneling. This adds an extra layer of security by protecting RADIUS attributes in transit. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SettingRadiusState.__new__(_SettingRadiusState)

        __props__.__dict__["accounting_enabled"] = accounting_enabled
        __props__.__dict__["accounting_port"] = accounting_port
        __props__.__dict__["auth_port"] = auth_port
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["interim_update_interval"] = interim_update_interval
        __props__.__dict__["secret"] = secret
        __props__.__dict__["site"] = site
        __props__.__dict__["tunneled_reply"] = tunneled_reply
        return SettingRadius(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountingEnabled")
    def accounting_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Enable RADIUS accounting to track user sessions, including connection time, data usage, and other metrics. This information can be useful for billing, capacity planning, and security auditing. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
        """
        return pulumi.get(self, "accounting_enabled")

    @_builtins.property
    @pulumi.getter(name="accountingPort")
    def accounting_port(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The UDP port number for RADIUS accounting communications. The standard port is 1813. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1813`" pulumi-lang-dotnet="`1813`" pulumi-lang-go="`1813`" pulumi-lang-python="`1813`" pulumi-lang-yaml="`1813`" pulumi-lang-java="`1813`" pulumi-lang-hcl="`1813`">`1813`</span>.
        """
        return pulumi.get(self, "accounting_port")

    @_builtins.property
    @pulumi.getter(name="authPort")
    def auth_port(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The UDP port number for RADIUS authentication communications. The standard port is 1812. Only change this if you need to avoid port conflicts or match specific network requirements. Defaults to <span pulumi-lang-nodejs="`1812`" pulumi-lang-dotnet="`1812`" pulumi-lang-go="`1812`" pulumi-lang-python="`1812`" pulumi-lang-yaml="`1812`" pulumi-lang-java="`1812`" pulumi-lang-hcl="`1812`">`1812`</span>.
        """
        return pulumi.get(self, "auth_port")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Enable or disable the built-in RADIUS server. When disabled, no RADIUS authentication or accounting services will be provided, affecting any network services that rely on RADIUS (like WPA2-Enterprise networks). Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="interimUpdateInterval")
    def interim_update_interval(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The interval (in seconds) at which the RADIUS server collects and updates statistics from connected clients. Default is 3600 seconds (1 hour). Lower values provide more frequent updates but increase server load. Defaults to <span pulumi-lang-nodejs="`3600`" pulumi-lang-dotnet="`3600`" pulumi-lang-go="`3600`" pulumi-lang-python="`3600`" pulumi-lang-yaml="`3600`" pulumi-lang-java="`3600`" pulumi-lang-hcl="`3600`">`3600`</span>.
        """
        return pulumi.get(self, "interim_update_interval")

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The shared secret passphrase used to authenticate RADIUS clients (like wireless access points) with the RADIUS server. This should be a strong, random string known only to the server and its clients. Defaults to ``.
        """
        return pulumi.get(self, "secret")

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the UniFi site where these RADIUS settings should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @_builtins.property
    @pulumi.getter(name="tunneledReply")
    def tunneled_reply(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Enable encrypted communication between the RADIUS server and clients using RADIUS tunneling. This adds an extra layer of security by protecting RADIUS attributes in transit. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
        """
        return pulumi.get(self, "tunneled_reply")

