# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SettingAutoSpeedtestArgs', 'SettingAutoSpeedtest']

@pulumi.input_type
class SettingAutoSpeedtestArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[_builtins.bool],
                 cron: pulumi.Input[Optional[_builtins.str]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a SettingAutoSpeedtest resource.

        :param pulumi.Input[_builtins.bool] enabled: Whether the automatic speedtest is enabled.
        :param pulumi.Input[_builtins.str] cron: Cron expression defining the schedule for automatic speedtests.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        pulumi.set(__self__, "enabled", enabled)
        if cron is not None:
            pulumi.set(__self__, "cron", cron)
        if site is not None:
            pulumi.set(__self__, "site", site)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        """
        Whether the automatic speedtest is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def cron(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cron expression defining the schedule for automatic speedtests.
        """
        return pulumi.get(self, "cron")

    @cron.setter
    def cron(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cron", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "site", value)


@pulumi.input_type
class _SettingAutoSpeedtestState:
    def __init__(__self__, *,
                 cron: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SettingAutoSpeedtest resources.

        :param pulumi.Input[_builtins.str] cron: Cron expression defining the schedule for automatic speedtests.
        :param pulumi.Input[_builtins.bool] enabled: Whether the automatic speedtest is enabled.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        if cron is not None:
            pulumi.set(__self__, "cron", cron)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if site is not None:
            pulumi.set(__self__, "site", site)

    @_builtins.property
    @pulumi.getter
    def cron(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cron expression defining the schedule for automatic speedtests.
        """
        return pulumi.get(self, "cron")

    @cron.setter
    def cron(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cron", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the automatic speedtest is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

    @site.setter
    def site(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "site", value)


@pulumi.type_token("unifi:index/settingAutoSpeedtest:SettingAutoSpeedtest")
class SettingAutoSpeedtest(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cron: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a SettingAutoSpeedtest resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cron: Cron expression defining the schedule for automatic speedtests.
        :param pulumi.Input[_builtins.bool] enabled: Whether the automatic speedtest is enabled.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SettingAutoSpeedtestArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SettingAutoSpeedtest resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SettingAutoSpeedtestArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SettingAutoSpeedtestArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cron: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 site: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SettingAutoSpeedtestArgs.__new__(SettingAutoSpeedtestArgs)

            __props__.__dict__["cron"] = cron
            if enabled is None and not opts.urn:
                raise TypeError("Missing required property 'enabled'")
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["site"] = site
        super(SettingAutoSpeedtest, __self__).__init__(
            'unifi:index/settingAutoSpeedtest:SettingAutoSpeedtest',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            cron: pulumi.Input[Optional[_builtins.str]] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            site: pulumi.Input[Optional[_builtins.str]] = None) -> 'SettingAutoSpeedtest':
        """
        Get an existing SettingAutoSpeedtest resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cron: Cron expression defining the schedule for automatic speedtests.
        :param pulumi.Input[_builtins.bool] enabled: Whether the automatic speedtest is enabled.
        :param pulumi.Input[_builtins.str] site: The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SettingAutoSpeedtestState.__new__(_SettingAutoSpeedtestState)

        __props__.__dict__["cron"] = cron
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["site"] = site
        return SettingAutoSpeedtest(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def cron(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Cron expression defining the schedule for automatic speedtests.
        """
        return pulumi.get(self, "cron")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the automatic speedtest is enabled.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def site(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        """
        return pulumi.get(self, "site")

