# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs
from ... import meta as _meta
from ._inputs import *

__all__ = ['FpgaDevicePluginArgs', 'FpgaDevicePlugin']

@pulumi.input_type
class FpgaDevicePluginArgs:
    def __init__(__self__, *,
                 api_version: Optional[pulumi.Input[str]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 metadata: Optional[pulumi.Input['_meta.v1.ObjectMetaArgs']] = None,
                 spec: Optional[pulumi.Input['FpgaDevicePluginSpecArgs']] = None,
                 status: Optional[pulumi.Input['FpgaDevicePluginStatusArgs']] = None):
        """
        The set of arguments for constructing a FpgaDevicePlugin resource.
        :param pulumi.Input['FpgaDevicePluginSpecArgs'] spec: FpgaDevicePluginSpec defines the desired state of FpgaDevicePlugin.
        :param pulumi.Input['FpgaDevicePluginStatusArgs'] status: FpgaDevicePluginStatus defines the observed state of FpgaDevicePlugin.
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'deviceplugin.intel.com/v1')
        if kind is not None:
            pulumi.set(__self__, "kind", 'FpgaDevicePlugin')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "api_version", value)

    @property
    @pulumi.getter
    def kind(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "kind", value)

    @property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input['_meta.v1.ObjectMetaArgs']]:
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input['_meta.v1.ObjectMetaArgs']]):
        pulumi.set(self, "metadata", value)

    @property
    @pulumi.getter
    def spec(self) -> Optional[pulumi.Input['FpgaDevicePluginSpecArgs']]:
        """
        FpgaDevicePluginSpec defines the desired state of FpgaDevicePlugin.
        """
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: Optional[pulumi.Input['FpgaDevicePluginSpecArgs']]):
        pulumi.set(self, "spec", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input['FpgaDevicePluginStatusArgs']]:
        """
        FpgaDevicePluginStatus defines the observed state of FpgaDevicePlugin.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input['FpgaDevicePluginStatusArgs']]):
        pulumi.set(self, "status", value)


class FpgaDevicePlugin(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: Optional[pulumi.Input[str]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 metadata: Optional[pulumi.Input[pulumi.InputType['_meta.v1.ObjectMetaArgs']]] = None,
                 spec: Optional[pulumi.Input[pulumi.InputType['FpgaDevicePluginSpecArgs']]] = None,
                 status: Optional[pulumi.Input[pulumi.InputType['FpgaDevicePluginStatusArgs']]] = None,
                 __props__=None):
        """
        FpgaDevicePlugin is the Schema for the fpgadeviceplugins API. It represents the FPGA device plugin responsible for advertising Intel FPGA hardware resources to the kubelet.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['FpgaDevicePluginSpecArgs']] spec: FpgaDevicePluginSpec defines the desired state of FpgaDevicePlugin.
        :param pulumi.Input[pulumi.InputType['FpgaDevicePluginStatusArgs']] status: FpgaDevicePluginStatus defines the observed state of FpgaDevicePlugin.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[FpgaDevicePluginArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        FpgaDevicePlugin is the Schema for the fpgadeviceplugins API. It represents the FPGA device plugin responsible for advertising Intel FPGA hardware resources to the kubelet.

        :param str resource_name: The name of the resource.
        :param FpgaDevicePluginArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FpgaDevicePluginArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: Optional[pulumi.Input[str]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 metadata: Optional[pulumi.Input[pulumi.InputType['_meta.v1.ObjectMetaArgs']]] = None,
                 spec: Optional[pulumi.Input[pulumi.InputType['FpgaDevicePluginSpecArgs']]] = None,
                 status: Optional[pulumi.Input[pulumi.InputType['FpgaDevicePluginStatusArgs']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FpgaDevicePluginArgs.__new__(FpgaDevicePluginArgs)

            __props__.__dict__["api_version"] = 'deviceplugin.intel.com/v1'
            __props__.__dict__["kind"] = 'FpgaDevicePlugin'
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["spec"] = spec
            __props__.__dict__["status"] = status
        super(FpgaDevicePlugin, __self__).__init__(
            'kubernetes:deviceplugin.intel.com/v1:FpgaDevicePlugin',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'FpgaDevicePlugin':
        """
        Get an existing FpgaDevicePlugin resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = FpgaDevicePluginArgs.__new__(FpgaDevicePluginArgs)

        __props__.__dict__["api_version"] = None
        __props__.__dict__["kind"] = None
        __props__.__dict__["metadata"] = None
        __props__.__dict__["spec"] = None
        __props__.__dict__["status"] = None
        return FpgaDevicePlugin(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "api_version")

    @property
    @pulumi.getter
    def kind(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "kind")

    @property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Optional['_meta.v1.outputs.ObjectMeta']]:
        return pulumi.get(self, "metadata")

    @property
    @pulumi.getter
    def spec(self) -> pulumi.Output[Optional['outputs.FpgaDevicePluginSpec']]:
        """
        FpgaDevicePluginSpec defines the desired state of FpgaDevicePlugin.
        """
        return pulumi.get(self, "spec")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[Optional['outputs.FpgaDevicePluginStatus']]:
        """
        FpgaDevicePluginStatus defines the observed state of FpgaDevicePlugin.
        """
        return pulumi.get(self, "status")

