# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities

__all__ = [
    'NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchExpressionsArgs',
    'NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchNameArgs',
    'NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesArgs',
    'NodeFeatureRuleSpecRulesMatchAnyArgs',
    'NodeFeatureRuleSpecRulesMatchFeaturesMatchExpressionsArgs',
    'NodeFeatureRuleSpecRulesMatchFeaturesMatchNameArgs',
    'NodeFeatureRuleSpecRulesMatchFeaturesArgs',
    'NodeFeatureRuleSpecRulesTaintsArgs',
    'NodeFeatureRuleSpecRulesArgs',
    'NodeFeatureRuleSpecArgs',
    'NodeFeatureSpecFeaturesAttributesArgs',
    'NodeFeatureSpecFeaturesFlagsArgs',
    'NodeFeatureSpecFeaturesInstancesElementsArgs',
    'NodeFeatureSpecFeaturesInstancesArgs',
    'NodeFeatureSpecFeaturesArgs',
    'NodeFeatureSpecArgs',
]

@pulumi.input_type
class NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchExpressionsArgs:
    def __init__(__self__, *,
                 op: pulumi.Input[str],
                 value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None):
        """
        MatchExpression specifies an expression to evaluate against a set of input values. It contains an operator that is applied when matching the input and an array of values that the operator evaluates the input against.
        :param pulumi.Input[str] op: Op is the operator to be applied.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] value: Value is the list of values that the operand evaluates the input against. Value should be empty if the operator is Exists, DoesNotExist, IsTrue or IsFalse. Value should contain exactly one element if the operator is Gt or Lt and exactly two elements if the operator is GtLt. In other cases Value should contain at least one element.
        """
        pulumi.set(__self__, "op", op)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def op(self) -> pulumi.Input[str]:
        """
        Op is the operator to be applied.
        """
        return pulumi.get(self, "op")

    @op.setter
    def op(self, value: pulumi.Input[str]):
        pulumi.set(self, "op", value)

    @property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Value is the list of values that the operand evaluates the input against. Value should be empty if the operator is Exists, DoesNotExist, IsTrue or IsFalse. Value should contain exactly one element if the operator is Gt or Lt and exactly two elements if the operator is GtLt. In other cases Value should contain at least one element.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "value", value)


@pulumi.input_type
class NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchNameArgs:
    def __init__(__self__, *,
                 op: pulumi.Input[str],
                 value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None):
        """
        MatchName in an expression that is matched against the name of each element in the feature set.
        :param pulumi.Input[str] op: Op is the operator to be applied.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] value: Value is the list of values that the operand evaluates the input against. Value should be empty if the operator is Exists, DoesNotExist, IsTrue or IsFalse. Value should contain exactly one element if the operator is Gt or Lt and exactly two elements if the operator is GtLt. In other cases Value should contain at least one element.
        """
        pulumi.set(__self__, "op", op)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def op(self) -> pulumi.Input[str]:
        """
        Op is the operator to be applied.
        """
        return pulumi.get(self, "op")

    @op.setter
    def op(self, value: pulumi.Input[str]):
        pulumi.set(self, "op", value)

    @property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Value is the list of values that the operand evaluates the input against. Value should be empty if the operator is Exists, DoesNotExist, IsTrue or IsFalse. Value should contain exactly one element if the operator is Gt or Lt and exactly two elements if the operator is GtLt. In other cases Value should contain at least one element.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "value", value)


@pulumi.input_type
class NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesArgs:
    def __init__(__self__, *,
                 feature: pulumi.Input[str],
                 match_expressions: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchExpressionsArgs']]]] = None,
                 match_name: Optional[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchNameArgs']] = None):
        """
        FeatureMatcherTerm defines requirements against one feature set. All requirements (specified as MatchExpressions) are evaluated against each element in the feature set.
        :param pulumi.Input[str] feature: Feature is the name of the feature set to match against.
        :param pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchExpressionsArgs']]] match_expressions: MatchExpressions is the set of per-element expressions evaluated. These match against the value of the specified elements.
        :param pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchNameArgs'] match_name: MatchName in an expression that is matched against the name of each element in the feature set.
        """
        pulumi.set(__self__, "feature", feature)
        if match_expressions is not None:
            pulumi.set(__self__, "match_expressions", match_expressions)
        if match_name is not None:
            pulumi.set(__self__, "match_name", match_name)

    @property
    @pulumi.getter
    def feature(self) -> pulumi.Input[str]:
        """
        Feature is the name of the feature set to match against.
        """
        return pulumi.get(self, "feature")

    @feature.setter
    def feature(self, value: pulumi.Input[str]):
        pulumi.set(self, "feature", value)

    @property
    @pulumi.getter(name="matchExpressions")
    def match_expressions(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchExpressionsArgs']]]]:
        """
        MatchExpressions is the set of per-element expressions evaluated. These match against the value of the specified elements.
        """
        return pulumi.get(self, "match_expressions")

    @match_expressions.setter
    def match_expressions(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchExpressionsArgs']]]]):
        pulumi.set(self, "match_expressions", value)

    @property
    @pulumi.getter(name="matchName")
    def match_name(self) -> Optional[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchNameArgs']]:
        """
        MatchName in an expression that is matched against the name of each element in the feature set.
        """
        return pulumi.get(self, "match_name")

    @match_name.setter
    def match_name(self, value: Optional[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesMatchNameArgs']]):
        pulumi.set(self, "match_name", value)


@pulumi.input_type
class NodeFeatureRuleSpecRulesMatchAnyArgs:
    def __init__(__self__, *,
                 match_features: pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesArgs']]]):
        """
        MatchAnyElem specifies one sub-matcher of MatchAny.
        :param pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesArgs']]] match_features: MatchFeatures specifies a set of matcher terms all of which must match.
        """
        pulumi.set(__self__, "match_features", match_features)

    @property
    @pulumi.getter(name="matchFeatures")
    def match_features(self) -> pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesArgs']]]:
        """
        MatchFeatures specifies a set of matcher terms all of which must match.
        """
        return pulumi.get(self, "match_features")

    @match_features.setter
    def match_features(self, value: pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyMatchFeaturesArgs']]]):
        pulumi.set(self, "match_features", value)


@pulumi.input_type
class NodeFeatureRuleSpecRulesMatchFeaturesMatchExpressionsArgs:
    def __init__(__self__, *,
                 op: pulumi.Input[str],
                 value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None):
        """
        MatchExpression specifies an expression to evaluate against a set of input values. It contains an operator that is applied when matching the input and an array of values that the operator evaluates the input against.
        :param pulumi.Input[str] op: Op is the operator to be applied.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] value: Value is the list of values that the operand evaluates the input against. Value should be empty if the operator is Exists, DoesNotExist, IsTrue or IsFalse. Value should contain exactly one element if the operator is Gt or Lt and exactly two elements if the operator is GtLt. In other cases Value should contain at least one element.
        """
        pulumi.set(__self__, "op", op)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def op(self) -> pulumi.Input[str]:
        """
        Op is the operator to be applied.
        """
        return pulumi.get(self, "op")

    @op.setter
    def op(self, value: pulumi.Input[str]):
        pulumi.set(self, "op", value)

    @property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Value is the list of values that the operand evaluates the input against. Value should be empty if the operator is Exists, DoesNotExist, IsTrue or IsFalse. Value should contain exactly one element if the operator is Gt or Lt and exactly two elements if the operator is GtLt. In other cases Value should contain at least one element.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "value", value)


@pulumi.input_type
class NodeFeatureRuleSpecRulesMatchFeaturesMatchNameArgs:
    def __init__(__self__, *,
                 op: pulumi.Input[str],
                 value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None):
        """
        MatchName in an expression that is matched against the name of each element in the feature set.
        :param pulumi.Input[str] op: Op is the operator to be applied.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] value: Value is the list of values that the operand evaluates the input against. Value should be empty if the operator is Exists, DoesNotExist, IsTrue or IsFalse. Value should contain exactly one element if the operator is Gt or Lt and exactly two elements if the operator is GtLt. In other cases Value should contain at least one element.
        """
        pulumi.set(__self__, "op", op)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def op(self) -> pulumi.Input[str]:
        """
        Op is the operator to be applied.
        """
        return pulumi.get(self, "op")

    @op.setter
    def op(self, value: pulumi.Input[str]):
        pulumi.set(self, "op", value)

    @property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Value is the list of values that the operand evaluates the input against. Value should be empty if the operator is Exists, DoesNotExist, IsTrue or IsFalse. Value should contain exactly one element if the operator is Gt or Lt and exactly two elements if the operator is GtLt. In other cases Value should contain at least one element.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "value", value)


@pulumi.input_type
class NodeFeatureRuleSpecRulesMatchFeaturesArgs:
    def __init__(__self__, *,
                 feature: pulumi.Input[str],
                 match_expressions: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesMatchExpressionsArgs']]]] = None,
                 match_name: Optional[pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesMatchNameArgs']] = None):
        """
        FeatureMatcherTerm defines requirements against one feature set. All requirements (specified as MatchExpressions) are evaluated against each element in the feature set.
        :param pulumi.Input[str] feature: Feature is the name of the feature set to match against.
        :param pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesMatchExpressionsArgs']]] match_expressions: MatchExpressions is the set of per-element expressions evaluated. These match against the value of the specified elements.
        :param pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesMatchNameArgs'] match_name: MatchName in an expression that is matched against the name of each element in the feature set.
        """
        pulumi.set(__self__, "feature", feature)
        if match_expressions is not None:
            pulumi.set(__self__, "match_expressions", match_expressions)
        if match_name is not None:
            pulumi.set(__self__, "match_name", match_name)

    @property
    @pulumi.getter
    def feature(self) -> pulumi.Input[str]:
        """
        Feature is the name of the feature set to match against.
        """
        return pulumi.get(self, "feature")

    @feature.setter
    def feature(self, value: pulumi.Input[str]):
        pulumi.set(self, "feature", value)

    @property
    @pulumi.getter(name="matchExpressions")
    def match_expressions(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesMatchExpressionsArgs']]]]:
        """
        MatchExpressions is the set of per-element expressions evaluated. These match against the value of the specified elements.
        """
        return pulumi.get(self, "match_expressions")

    @match_expressions.setter
    def match_expressions(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesMatchExpressionsArgs']]]]):
        pulumi.set(self, "match_expressions", value)

    @property
    @pulumi.getter(name="matchName")
    def match_name(self) -> Optional[pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesMatchNameArgs']]:
        """
        MatchName in an expression that is matched against the name of each element in the feature set.
        """
        return pulumi.get(self, "match_name")

    @match_name.setter
    def match_name(self, value: Optional[pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesMatchNameArgs']]):
        pulumi.set(self, "match_name", value)


@pulumi.input_type
class NodeFeatureRuleSpecRulesTaintsArgs:
    def __init__(__self__, *,
                 effect: pulumi.Input[str],
                 key: pulumi.Input[str],
                 time_added: Optional[pulumi.Input[str]] = None,
                 value: Optional[pulumi.Input[str]] = None):
        """
        The node this Taint is attached to has the "effect" on any pod that does not tolerate the Taint.
        :param pulumi.Input[str] effect: Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
        :param pulumi.Input[str] key: Required. The taint key to be applied to a node.
        :param pulumi.Input[str] time_added: TimeAdded represents the time at which the taint was added. It is only written for NoExecute taints.
        :param pulumi.Input[str] value: The taint value corresponding to the taint key.
        """
        pulumi.set(__self__, "effect", effect)
        pulumi.set(__self__, "key", key)
        if time_added is not None:
            pulumi.set(__self__, "time_added", time_added)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def effect(self) -> pulumi.Input[str]:
        """
        Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
        """
        return pulumi.get(self, "effect")

    @effect.setter
    def effect(self, value: pulumi.Input[str]):
        pulumi.set(self, "effect", value)

    @property
    @pulumi.getter
    def key(self) -> pulumi.Input[str]:
        """
        Required. The taint key to be applied to a node.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[str]):
        pulumi.set(self, "key", value)

    @property
    @pulumi.getter(name="timeAdded")
    def time_added(self) -> Optional[pulumi.Input[str]]:
        """
        TimeAdded represents the time at which the taint was added. It is only written for NoExecute taints.
        """
        return pulumi.get(self, "time_added")

    @time_added.setter
    def time_added(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "time_added", value)

    @property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[str]]:
        """
        The taint value corresponding to the taint key.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "value", value)


@pulumi.input_type
class NodeFeatureRuleSpecRulesArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 annotations: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 extended_resources: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 labels_template: Optional[pulumi.Input[str]] = None,
                 match_any: Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyArgs']]]] = None,
                 match_features: Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesArgs']]]] = None,
                 taints: Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesTaintsArgs']]]] = None,
                 vars: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 vars_template: Optional[pulumi.Input[str]] = None):
        """
        Rule defines a rule for node customization such as labeling.
        :param pulumi.Input[str] name: Name of the rule.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] annotations: Annotations to create if the rule matches.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] extended_resources: ExtendedResources to create if the rule matches.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Labels to create if the rule matches.
        :param pulumi.Input[str] labels_template: LabelsTemplate specifies a template to expand for dynamically generating multiple labels. Data (after template expansion) must be keys with an optional value (<key>[=<value>]) separated by newlines.
        :param pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyArgs']]] match_any: MatchAny specifies a list of matchers one of which must match.
        :param pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesArgs']]] match_features: MatchFeatures specifies a set of matcher terms all of which must match.
        :param pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesTaintsArgs']]] taints: Taints to create if the rule matches.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] vars: Vars is the variables to store if the rule matches. Variables do not directly inflict any changes in the node object. However, they can be referenced from other rules enabling more complex rule hierarchies, without exposing intermediary output values as labels.
        :param pulumi.Input[str] vars_template: VarsTemplate specifies a template to expand for dynamically generating multiple variables. Data (after template expansion) must be keys with an optional value (<key>[=<value>]) separated by newlines.
        """
        pulumi.set(__self__, "name", name)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if extended_resources is not None:
            pulumi.set(__self__, "extended_resources", extended_resources)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if labels_template is not None:
            pulumi.set(__self__, "labels_template", labels_template)
        if match_any is not None:
            pulumi.set(__self__, "match_any", match_any)
        if match_features is not None:
            pulumi.set(__self__, "match_features", match_features)
        if taints is not None:
            pulumi.set(__self__, "taints", taints)
        if vars is not None:
            pulumi.set(__self__, "vars", vars)
        if vars_template is not None:
            pulumi.set(__self__, "vars_template", vars_template)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        Name of the rule.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Annotations to create if the rule matches.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "annotations", value)

    @property
    @pulumi.getter(name="extendedResources")
    def extended_resources(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        ExtendedResources to create if the rule matches.
        """
        return pulumi.get(self, "extended_resources")

    @extended_resources.setter
    def extended_resources(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "extended_resources", value)

    @property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Labels to create if the rule matches.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "labels", value)

    @property
    @pulumi.getter(name="labelsTemplate")
    def labels_template(self) -> Optional[pulumi.Input[str]]:
        """
        LabelsTemplate specifies a template to expand for dynamically generating multiple labels. Data (after template expansion) must be keys with an optional value (<key>[=<value>]) separated by newlines.
        """
        return pulumi.get(self, "labels_template")

    @labels_template.setter
    def labels_template(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "labels_template", value)

    @property
    @pulumi.getter(name="matchAny")
    def match_any(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyArgs']]]]:
        """
        MatchAny specifies a list of matchers one of which must match.
        """
        return pulumi.get(self, "match_any")

    @match_any.setter
    def match_any(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchAnyArgs']]]]):
        pulumi.set(self, "match_any", value)

    @property
    @pulumi.getter(name="matchFeatures")
    def match_features(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesArgs']]]]:
        """
        MatchFeatures specifies a set of matcher terms all of which must match.
        """
        return pulumi.get(self, "match_features")

    @match_features.setter
    def match_features(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesMatchFeaturesArgs']]]]):
        pulumi.set(self, "match_features", value)

    @property
    @pulumi.getter
    def taints(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesTaintsArgs']]]]:
        """
        Taints to create if the rule matches.
        """
        return pulumi.get(self, "taints")

    @taints.setter
    def taints(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesTaintsArgs']]]]):
        pulumi.set(self, "taints", value)

    @property
    @pulumi.getter
    def vars(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Vars is the variables to store if the rule matches. Variables do not directly inflict any changes in the node object. However, they can be referenced from other rules enabling more complex rule hierarchies, without exposing intermediary output values as labels.
        """
        return pulumi.get(self, "vars")

    @vars.setter
    def vars(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "vars", value)

    @property
    @pulumi.getter(name="varsTemplate")
    def vars_template(self) -> Optional[pulumi.Input[str]]:
        """
        VarsTemplate specifies a template to expand for dynamically generating multiple variables. Data (after template expansion) must be keys with an optional value (<key>[=<value>]) separated by newlines.
        """
        return pulumi.get(self, "vars_template")

    @vars_template.setter
    def vars_template(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "vars_template", value)


@pulumi.input_type
class NodeFeatureRuleSpecArgs:
    def __init__(__self__, *,
                 rules: pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesArgs']]]):
        """
        NodeFeatureRuleSpec describes a NodeFeatureRule.
        :param pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesArgs']]] rules: Rules is a list of node customization rules.
        """
        pulumi.set(__self__, "rules", rules)

    @property
    @pulumi.getter
    def rules(self) -> pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesArgs']]]:
        """
        Rules is a list of node customization rules.
        """
        return pulumi.get(self, "rules")

    @rules.setter
    def rules(self, value: pulumi.Input[Sequence[pulumi.Input['NodeFeatureRuleSpecRulesArgs']]]):
        pulumi.set(self, "rules", value)


@pulumi.input_type
class NodeFeatureSpecFeaturesAttributesArgs:
    def __init__(__self__, *,
                 elements: pulumi.Input[Mapping[str, pulumi.Input[str]]]):
        """
        AttributeFeatureSet is a set of features having string value.
        """
        pulumi.set(__self__, "elements", elements)

    @property
    @pulumi.getter
    def elements(self) -> pulumi.Input[Mapping[str, pulumi.Input[str]]]:
        return pulumi.get(self, "elements")

    @elements.setter
    def elements(self, value: pulumi.Input[Mapping[str, pulumi.Input[str]]]):
        pulumi.set(self, "elements", value)


@pulumi.input_type
class NodeFeatureSpecFeaturesFlagsArgs:
    def __init__(__self__, *,
                 elements: pulumi.Input[Mapping[str, pulumi.Input[Mapping[str, Any]]]]):
        """
        FlagFeatureSet is a set of simple features only containing names without values.
        """
        pulumi.set(__self__, "elements", elements)

    @property
    @pulumi.getter
    def elements(self) -> pulumi.Input[Mapping[str, pulumi.Input[Mapping[str, Any]]]]:
        return pulumi.get(self, "elements")

    @elements.setter
    def elements(self, value: pulumi.Input[Mapping[str, pulumi.Input[Mapping[str, Any]]]]):
        pulumi.set(self, "elements", value)


@pulumi.input_type
class NodeFeatureSpecFeaturesInstancesElementsArgs:
    def __init__(__self__, *,
                 attributes: pulumi.Input[Mapping[str, pulumi.Input[str]]]):
        """
        InstanceFeature represents one instance of a complex features, e.g. a device.
        """
        pulumi.set(__self__, "attributes", attributes)

    @property
    @pulumi.getter
    def attributes(self) -> pulumi.Input[Mapping[str, pulumi.Input[str]]]:
        return pulumi.get(self, "attributes")

    @attributes.setter
    def attributes(self, value: pulumi.Input[Mapping[str, pulumi.Input[str]]]):
        pulumi.set(self, "attributes", value)


@pulumi.input_type
class NodeFeatureSpecFeaturesInstancesArgs:
    def __init__(__self__, *,
                 elements: pulumi.Input[Sequence[pulumi.Input['NodeFeatureSpecFeaturesInstancesElementsArgs']]]):
        """
        InstanceFeatureSet is a set of features each of which is an instance having multiple attributes.
        """
        pulumi.set(__self__, "elements", elements)

    @property
    @pulumi.getter
    def elements(self) -> pulumi.Input[Sequence[pulumi.Input['NodeFeatureSpecFeaturesInstancesElementsArgs']]]:
        return pulumi.get(self, "elements")

    @elements.setter
    def elements(self, value: pulumi.Input[Sequence[pulumi.Input['NodeFeatureSpecFeaturesInstancesElementsArgs']]]):
        pulumi.set(self, "elements", value)


@pulumi.input_type
class NodeFeatureSpecFeaturesArgs:
    def __init__(__self__, *,
                 attributes: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesAttributesArgs']]]] = None,
                 flags: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesFlagsArgs']]]] = None,
                 instances: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesInstancesArgs']]]] = None):
        """
        Features is the full "raw" features data that has been discovered.
        :param pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesAttributesArgs']]] attributes: Attributes contains all the attribute-type features of the node.
        :param pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesFlagsArgs']]] flags: Flags contains all the flag-type features of the node.
        :param pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesInstancesArgs']]] instances: Instances contains all the instance-type features of the node.
        """
        if attributes is not None:
            pulumi.set(__self__, "attributes", attributes)
        if flags is not None:
            pulumi.set(__self__, "flags", flags)
        if instances is not None:
            pulumi.set(__self__, "instances", instances)

    @property
    @pulumi.getter
    def attributes(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesAttributesArgs']]]]:
        """
        Attributes contains all the attribute-type features of the node.
        """
        return pulumi.get(self, "attributes")

    @attributes.setter
    def attributes(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesAttributesArgs']]]]):
        pulumi.set(self, "attributes", value)

    @property
    @pulumi.getter
    def flags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesFlagsArgs']]]]:
        """
        Flags contains all the flag-type features of the node.
        """
        return pulumi.get(self, "flags")

    @flags.setter
    def flags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesFlagsArgs']]]]):
        pulumi.set(self, "flags", value)

    @property
    @pulumi.getter
    def instances(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesInstancesArgs']]]]:
        """
        Instances contains all the instance-type features of the node.
        """
        return pulumi.get(self, "instances")

    @instances.setter
    def instances(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['NodeFeatureSpecFeaturesInstancesArgs']]]]):
        pulumi.set(self, "instances", value)


@pulumi.input_type
class NodeFeatureSpecArgs:
    def __init__(__self__, *,
                 features: Optional[pulumi.Input['NodeFeatureSpecFeaturesArgs']] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None):
        """
        NodeFeatureSpec describes a NodeFeature object.
        :param pulumi.Input['NodeFeatureSpecFeaturesArgs'] features: Features is the full "raw" features data that has been discovered.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Labels is the set of node labels that are requested to be created.
        """
        if features is not None:
            pulumi.set(__self__, "features", features)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)

    @property
    @pulumi.getter
    def features(self) -> Optional[pulumi.Input['NodeFeatureSpecFeaturesArgs']]:
        """
        Features is the full "raw" features data that has been discovered.
        """
        return pulumi.get(self, "features")

    @features.setter
    def features(self, value: Optional[pulumi.Input['NodeFeatureSpecFeaturesArgs']]):
        pulumi.set(self, "features", value)

    @property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Labels is the set of node labels that are requested to be created.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "labels", value)


