# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ... import meta as _meta

__all__ = [
    'SealedSecret',
    'SealedSecretSpec',
    'SealedSecretSpecPatch',
    'SealedSecretSpecTemplate',
    'SealedSecretSpecTemplatePatch',
    'SealedSecretStatus',
    'SealedSecretStatusConditions',
    'SealedSecretStatusConditionsPatch',
    'SealedSecretStatusPatch',
]

@pulumi.output_type
class SealedSecret(dict):
    """
    SealedSecret is the K8s representation of a "sealed Secret" - a
    regular k8s Secret that has been sealed (encrypted) using the
    controller's key.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "apiVersion":
            suggest = "api_version"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SealedSecret. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SealedSecret.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SealedSecret.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 api_version: Optional[_builtins.str] = None,
                 kind: Optional[_builtins.str] = None,
                 metadata: Optional['_meta.v1.outputs.ObjectMeta'] = None,
                 spec: Optional['outputs.SealedSecretSpec'] = None,
                 status: Optional['outputs.SealedSecretStatus'] = None):
        """
        SealedSecret is the K8s representation of a "sealed Secret" - a
        regular k8s Secret that has been sealed (encrypted) using the
        controller's key.

        :param _builtins.str api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param _builtins.str kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param '_meta.v1.ObjectMetaArgs' metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'bitnami.com/v1alpha1')
        if kind is not None:
            pulumi.set(__self__, "kind", 'SealedSecret')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> Optional[_builtins.str]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> Optional[_builtins.str]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional['_meta.v1.outputs.ObjectMeta']:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def spec(self) -> Optional['outputs.SealedSecretSpec']:
        return pulumi.get(self, "spec")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional['outputs.SealedSecretStatus']:
        return pulumi.get(self, "status")


@pulumi.output_type
class SealedSecretSpec(dict):
    """
    SealedSecretSpec is the specification of a SealedSecret.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "encryptedData":
            suggest = "encrypted_data"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SealedSecretSpec. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SealedSecretSpec.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SealedSecretSpec.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 data: Optional[_builtins.str] = None,
                 encrypted_data: Optional[Mapping[str, Any]] = None,
                 template: Optional['outputs.SealedSecretSpecTemplate'] = None):
        """
        SealedSecretSpec is the specification of a SealedSecret.

        :param _builtins.str data: Data is deprecated and will be removed eventually. Use per-value EncryptedData instead.
        """
        if data is not None:
            pulumi.set(__self__, "data", data)
        if encrypted_data is not None:
            pulumi.set(__self__, "encrypted_data", encrypted_data)
        if template is not None:
            pulumi.set(__self__, "template", template)

    @_builtins.property
    @pulumi.getter
    def data(self) -> Optional[_builtins.str]:
        """
        Data is deprecated and will be removed eventually. Use per-value EncryptedData instead.
        """
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter(name="encryptedData")
    def encrypted_data(self) -> Optional[Mapping[str, Any]]:
        return pulumi.get(self, "encrypted_data")

    @_builtins.property
    @pulumi.getter
    def template(self) -> Optional['outputs.SealedSecretSpecTemplate']:
        return pulumi.get(self, "template")


@pulumi.output_type
class SealedSecretSpecPatch(dict):
    """
    SealedSecretSpec is the specification of a SealedSecret.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "encryptedData":
            suggest = "encrypted_data"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SealedSecretSpecPatch. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SealedSecretSpecPatch.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SealedSecretSpecPatch.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 data: Optional[_builtins.str] = None,
                 encrypted_data: Optional[Mapping[str, Any]] = None,
                 template: Optional['outputs.SealedSecretSpecTemplatePatch'] = None):
        """
        SealedSecretSpec is the specification of a SealedSecret.

        :param _builtins.str data: Data is deprecated and will be removed eventually. Use per-value EncryptedData instead.
        """
        if data is not None:
            pulumi.set(__self__, "data", data)
        if encrypted_data is not None:
            pulumi.set(__self__, "encrypted_data", encrypted_data)
        if template is not None:
            pulumi.set(__self__, "template", template)

    @_builtins.property
    @pulumi.getter
    def data(self) -> Optional[_builtins.str]:
        """
        Data is deprecated and will be removed eventually. Use per-value EncryptedData instead.
        """
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter(name="encryptedData")
    def encrypted_data(self) -> Optional[Mapping[str, Any]]:
        return pulumi.get(self, "encrypted_data")

    @_builtins.property
    @pulumi.getter
    def template(self) -> Optional['outputs.SealedSecretSpecTemplatePatch']:
        return pulumi.get(self, "template")


@pulumi.output_type
class SealedSecretSpecTemplate(dict):
    """
    Template defines the structure of the Secret that will be
    created from this sealed secret.
    """
    def __init__(__self__, *,
                 data: Optional[Mapping[str, _builtins.str]] = None,
                 immutable: Optional[_builtins.bool] = None,
                 metadata: Optional[Mapping[str, Any]] = None,
                 type: Optional[_builtins.str] = None):
        """
        Template defines the structure of the Secret that will be
        created from this sealed secret.

        :param Mapping[str, _builtins.str] data: Keys that should be templated using decrypted data.
        :param _builtins.bool immutable: Immutable, if set to true, ensures that data stored in the Secret cannot
               be updated (only object metadata can be modified).
               If not set to true, the field can be modified at any time.
               Defaulted to nil.
        :param Mapping[str, Any] metadata: Standard object's metadata.
               More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param _builtins.str type: Used to facilitate programmatic handling of secret data.
        """
        if data is not None:
            pulumi.set(__self__, "data", data)
        if immutable is not None:
            pulumi.set(__self__, "immutable", immutable)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def data(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Keys that should be templated using decrypted data.
        """
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter
    def immutable(self) -> Optional[_builtins.bool]:
        """
        Immutable, if set to true, ensures that data stored in the Secret cannot
        be updated (only object metadata can be modified).
        If not set to true, the field can be modified at any time.
        Defaulted to nil.
        """
        return pulumi.get(self, "immutable")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[Mapping[str, Any]]:
        """
        Standard object's metadata.
        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        Used to facilitate programmatic handling of secret data.
        """
        return pulumi.get(self, "type")


@pulumi.output_type
class SealedSecretSpecTemplatePatch(dict):
    """
    Template defines the structure of the Secret that will be
    created from this sealed secret.
    """
    def __init__(__self__, *,
                 data: Optional[Mapping[str, _builtins.str]] = None,
                 immutable: Optional[_builtins.bool] = None,
                 metadata: Optional[Mapping[str, Any]] = None,
                 type: Optional[_builtins.str] = None):
        """
        Template defines the structure of the Secret that will be
        created from this sealed secret.

        :param Mapping[str, _builtins.str] data: Keys that should be templated using decrypted data.
        :param _builtins.bool immutable: Immutable, if set to true, ensures that data stored in the Secret cannot
               be updated (only object metadata can be modified).
               If not set to true, the field can be modified at any time.
               Defaulted to nil.
        :param Mapping[str, Any] metadata: Standard object's metadata.
               More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        :param _builtins.str type: Used to facilitate programmatic handling of secret data.
        """
        if data is not None:
            pulumi.set(__self__, "data", data)
        if immutable is not None:
            pulumi.set(__self__, "immutable", immutable)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def data(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Keys that should be templated using decrypted data.
        """
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter
    def immutable(self) -> Optional[_builtins.bool]:
        """
        Immutable, if set to true, ensures that data stored in the Secret cannot
        be updated (only object metadata can be modified).
        If not set to true, the field can be modified at any time.
        Defaulted to nil.
        """
        return pulumi.get(self, "immutable")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[Mapping[str, Any]]:
        """
        Standard object's metadata.
        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        Used to facilitate programmatic handling of secret data.
        """
        return pulumi.get(self, "type")


@pulumi.output_type
class SealedSecretStatus(dict):
    """
    SealedSecretStatus is the most recently observed status of the SealedSecret.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "observedGeneration":
            suggest = "observed_generation"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SealedSecretStatus. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SealedSecretStatus.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SealedSecretStatus.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 conditions: Optional[Sequence['outputs.SealedSecretStatusConditions']] = None,
                 observed_generation: Optional[_builtins.int] = None):
        """
        SealedSecretStatus is the most recently observed status of the SealedSecret.

        :param Sequence['SealedSecretStatusConditionsArgs'] conditions: Represents the latest available observations of a sealed secret's current state.
        :param _builtins.int observed_generation: ObservedGeneration reflects the generation most recently observed by the sealed-secrets controller.
        """
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if observed_generation is not None:
            pulumi.set(__self__, "observed_generation", observed_generation)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> Optional[Sequence['outputs.SealedSecretStatusConditions']]:
        """
        Represents the latest available observations of a sealed secret's current state.
        """
        return pulumi.get(self, "conditions")

    @_builtins.property
    @pulumi.getter(name="observedGeneration")
    def observed_generation(self) -> Optional[_builtins.int]:
        """
        ObservedGeneration reflects the generation most recently observed by the sealed-secrets controller.
        """
        return pulumi.get(self, "observed_generation")


@pulumi.output_type
class SealedSecretStatusConditions(dict):
    """
    SealedSecretCondition describes the state of a sealed secret at a certain point.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "lastTransitionTime":
            suggest = "last_transition_time"
        elif key == "lastUpdateTime":
            suggest = "last_update_time"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SealedSecretStatusConditions. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SealedSecretStatusConditions.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SealedSecretStatusConditions.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 last_transition_time: Optional[_builtins.str] = None,
                 last_update_time: Optional[_builtins.str] = None,
                 message: Optional[_builtins.str] = None,
                 reason: Optional[_builtins.str] = None,
                 status: Optional[_builtins.str] = None,
                 type: Optional[_builtins.str] = None):
        """
        SealedSecretCondition describes the state of a sealed secret at a certain point.

        :param _builtins.str last_transition_time: Last time the condition transitioned from one status to another.
        :param _builtins.str last_update_time: The last time this condition was updated.
        :param _builtins.str message: A human readable message indicating details about the transition.
        :param _builtins.str reason: The reason for the condition's last transition.
        :param _builtins.str status: Status of the condition for a sealed secret.
               Valid values for "Synced": "True", "False", or "Unknown".
        :param _builtins.str type: Type of condition for a sealed secret.
               Valid value: "Synced"
        """
        if last_transition_time is not None:
            pulumi.set(__self__, "last_transition_time", last_transition_time)
        if last_update_time is not None:
            pulumi.set(__self__, "last_update_time", last_update_time)
        if message is not None:
            pulumi.set(__self__, "message", message)
        if reason is not None:
            pulumi.set(__self__, "reason", reason)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="lastTransitionTime")
    def last_transition_time(self) -> Optional[_builtins.str]:
        """
        Last time the condition transitioned from one status to another.
        """
        return pulumi.get(self, "last_transition_time")

    @_builtins.property
    @pulumi.getter(name="lastUpdateTime")
    def last_update_time(self) -> Optional[_builtins.str]:
        """
        The last time this condition was updated.
        """
        return pulumi.get(self, "last_update_time")

    @_builtins.property
    @pulumi.getter
    def message(self) -> Optional[_builtins.str]:
        """
        A human readable message indicating details about the transition.
        """
        return pulumi.get(self, "message")

    @_builtins.property
    @pulumi.getter
    def reason(self) -> Optional[_builtins.str]:
        """
        The reason for the condition's last transition.
        """
        return pulumi.get(self, "reason")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        """
        Status of the condition for a sealed secret.
        Valid values for "Synced": "True", "False", or "Unknown".
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        Type of condition for a sealed secret.
        Valid value: "Synced"
        """
        return pulumi.get(self, "type")


@pulumi.output_type
class SealedSecretStatusConditionsPatch(dict):
    """
    SealedSecretCondition describes the state of a sealed secret at a certain point.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "lastTransitionTime":
            suggest = "last_transition_time"
        elif key == "lastUpdateTime":
            suggest = "last_update_time"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SealedSecretStatusConditionsPatch. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SealedSecretStatusConditionsPatch.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SealedSecretStatusConditionsPatch.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 last_transition_time: Optional[_builtins.str] = None,
                 last_update_time: Optional[_builtins.str] = None,
                 message: Optional[_builtins.str] = None,
                 reason: Optional[_builtins.str] = None,
                 status: Optional[_builtins.str] = None,
                 type: Optional[_builtins.str] = None):
        """
        SealedSecretCondition describes the state of a sealed secret at a certain point.

        :param _builtins.str last_transition_time: Last time the condition transitioned from one status to another.
        :param _builtins.str last_update_time: The last time this condition was updated.
        :param _builtins.str message: A human readable message indicating details about the transition.
        :param _builtins.str reason: The reason for the condition's last transition.
        :param _builtins.str status: Status of the condition for a sealed secret.
               Valid values for "Synced": "True", "False", or "Unknown".
        :param _builtins.str type: Type of condition for a sealed secret.
               Valid value: "Synced"
        """
        if last_transition_time is not None:
            pulumi.set(__self__, "last_transition_time", last_transition_time)
        if last_update_time is not None:
            pulumi.set(__self__, "last_update_time", last_update_time)
        if message is not None:
            pulumi.set(__self__, "message", message)
        if reason is not None:
            pulumi.set(__self__, "reason", reason)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="lastTransitionTime")
    def last_transition_time(self) -> Optional[_builtins.str]:
        """
        Last time the condition transitioned from one status to another.
        """
        return pulumi.get(self, "last_transition_time")

    @_builtins.property
    @pulumi.getter(name="lastUpdateTime")
    def last_update_time(self) -> Optional[_builtins.str]:
        """
        The last time this condition was updated.
        """
        return pulumi.get(self, "last_update_time")

    @_builtins.property
    @pulumi.getter
    def message(self) -> Optional[_builtins.str]:
        """
        A human readable message indicating details about the transition.
        """
        return pulumi.get(self, "message")

    @_builtins.property
    @pulumi.getter
    def reason(self) -> Optional[_builtins.str]:
        """
        The reason for the condition's last transition.
        """
        return pulumi.get(self, "reason")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        """
        Status of the condition for a sealed secret.
        Valid values for "Synced": "True", "False", or "Unknown".
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        Type of condition for a sealed secret.
        Valid value: "Synced"
        """
        return pulumi.get(self, "type")


@pulumi.output_type
class SealedSecretStatusPatch(dict):
    """
    SealedSecretStatus is the most recently observed status of the SealedSecret.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "observedGeneration":
            suggest = "observed_generation"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SealedSecretStatusPatch. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SealedSecretStatusPatch.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SealedSecretStatusPatch.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 conditions: Optional[Sequence['outputs.SealedSecretStatusConditionsPatch']] = None,
                 observed_generation: Optional[_builtins.int] = None):
        """
        SealedSecretStatus is the most recently observed status of the SealedSecret.

        :param Sequence['SealedSecretStatusConditionsPatchArgs'] conditions: Represents the latest available observations of a sealed secret's current state.
        :param _builtins.int observed_generation: ObservedGeneration reflects the generation most recently observed by the sealed-secrets controller.
        """
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if observed_generation is not None:
            pulumi.set(__self__, "observed_generation", observed_generation)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> Optional[Sequence['outputs.SealedSecretStatusConditionsPatch']]:
        """
        Represents the latest available observations of a sealed secret's current state.
        """
        return pulumi.get(self, "conditions")

    @_builtins.property
    @pulumi.getter(name="observedGeneration")
    def observed_generation(self) -> Optional[_builtins.int]:
        """
        ObservedGeneration reflects the generation most recently observed by the sealed-secrets controller.
        """
        return pulumi.get(self, "observed_generation")


